// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/user/v2/pat.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.User.V2 {

  /// <summary>Holder for reflection information generated from zitadel/user/v2/pat.proto</summary>
  public static partial class PatReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/user/v2/pat.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PatReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chl6aXRhZGVsL3VzZXIvdjIvcGF0LnByb3RvEg96aXRhZGVsLnVzZXIudjIa",
            "LnByb3RvYy1nZW4tb3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJv",
            "dG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAucHJvdG8aF3ZhbGlkYXRl",
            "L3ZhbGlkYXRlLnByb3RvGh56aXRhZGVsL2ZpbHRlci92Mi9maWx0ZXIucHJv",
            "dG8i2wMKE1BlcnNvbmFsQWNjZXNzVG9rZW4SYAoNY3JlYXRpb25fZGF0ZRgB",
            "IAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCH5JBHEoaIjIwMjQt",
            "MTItMThUMDc6NTA6NDcuNDkyWiJSDGNyZWF0aW9uRGF0ZRJcCgtjaGFuZ2Vf",
            "ZGF0ZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCH5JBHEoa",
            "IjIwMjQtMTItMThUMDc6NTA6NDcuNDkyWiJSCmNoYW5nZURhdGUSKAoCaWQY",
            "AyABKAlCGJJBFUoTIjY5NjI5MDEyOTA2NDg4MzM0IlICaWQSMQoHdXNlcl9p",
            "ZBgEIAEoCUIYkkEVShMiNjk2MjkwMTI5MDY0ODgzMzQiUgZ1c2VySWQSQQoP",
            "b3JnYW5pemF0aW9uX2lkGAUgASgJQhiSQRVKEyI2OTYyOTAxMjkwNjQ4ODMz",
            "NCJSDm9yZ2FuaXphdGlvbklkEmQKD2V4cGlyYXRpb25fZGF0ZRgGIAEoCzIa",
            "Lmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCH5JBHEoaIjIwMjQtMTItMThU",
            "MDc6NTA6NDcuNDkyWiJSDmV4cGlyYXRpb25EYXRlIsQDCiBQZXJzb25hbEFj",
            "Y2Vzc1Rva2Vuc1NlYXJjaEZpbHRlchJFCg90b2tlbl9pZF9maWx0ZXIYASAB",
            "KAsyGy56aXRhZGVsLmZpbHRlci52Mi5JREZpbHRlckgAUg10b2tlbklkRmls",
            "dGVyEkMKDnVzZXJfaWRfZmlsdGVyGAIgASgLMhsueml0YWRlbC5maWx0ZXIu",
            "djIuSURGaWx0ZXJIAFIMdXNlcklkRmlsdGVyElMKFm9yZ2FuaXphdGlvbl9p",
            "ZF9maWx0ZXIYAyABKAsyGy56aXRhZGVsLmZpbHRlci52Mi5JREZpbHRlckgA",
            "UhRvcmdhbml6YXRpb25JZEZpbHRlchJUChNjcmVhdGVkX2RhdGVfZmlsdGVy",
            "GAQgASgLMiIueml0YWRlbC5maWx0ZXIudjIuVGltZXN0YW1wRmlsdGVySABS",
            "EWNyZWF0ZWREYXRlRmlsdGVyEloKFmV4cGlyYXRpb25fZGF0ZV9maWx0ZXIY",
            "BSABKAsyIi56aXRhZGVsLmZpbHRlci52Mi5UaW1lc3RhbXBGaWx0ZXJIAFIU",
            "ZXhwaXJhdGlvbkRhdGVGaWx0ZXJCDQoGZmlsdGVyEgP4QgEqxgIKHFBlcnNv",
            "bmFsQWNjZXNzVG9rZW5GaWVsZE5hbWUSMAosUEVSU09OQUxfQUNDRVNTX1RP",
            "S0VOX0ZJRUxEX05BTUVfVU5TUEVDSUZJRUQQABIxCi1QRVJTT05BTF9BQ0NF",
            "U1NfVE9LRU5fRklFTERfTkFNRV9DUkVBVEVEX0RBVEUQARInCiNQRVJTT05B",
            "TF9BQ0NFU1NfVE9LRU5fRklFTERfTkFNRV9JRBACEiwKKFBFUlNPTkFMX0FD",
            "Q0VTU19UT0tFTl9GSUVMRF9OQU1FX1VTRVJfSUQQAxI0CjBQRVJTT05BTF9B",
            "Q0NFU1NfVE9LRU5fRklFTERfTkFNRV9PUkdBTklaQVRJT05fSUQQBBI0CjBQ",
            "RVJTT05BTF9BQ0NFU1NfVE9LRU5fRklFTERfTkFNRV9FWFBJUkFUSU9OX0RB",
            "VEUQBUKvAQoTY29tLnppdGFkZWwudXNlci52MkIIUGF0UHJvdG9QAVowZ2l0",
            "aHViLmNvbS96aXRhZGVsL3ppdGFkZWwvcGtnL2dycGMvdXNlci92Mjt1c2Vy",
            "ogIDWlVYqgIPWml0YWRlbC5Vc2VyLlYyygIPWml0YWRlbFxVc2VyXFYy4gIb",
            "Wml0YWRlbFxVc2VyXFYyXEdQQk1ldGFkYXRh6gIRWml0YWRlbDo6VXNlcjo6",
            "VjJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Zitadel.Filter.V2.FilterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zitadel.User.V2.PersonalAccessTokenFieldName), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.User.V2.PersonalAccessToken), global::Zitadel.User.V2.PersonalAccessToken.Parser, new[]{ "CreationDate", "ChangeDate", "Id", "UserId", "OrganizationId", "ExpirationDate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.User.V2.PersonalAccessTokensSearchFilter), global::Zitadel.User.V2.PersonalAccessTokensSearchFilter.Parser, new[]{ "TokenIdFilter", "UserIdFilter", "OrganizationIdFilter", "CreatedDateFilter", "ExpirationDateFilter" }, new[]{ "Filter" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PersonalAccessTokenFieldName {
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_CREATED_DATE")] CreatedDate = 1,
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_ID")] Id = 2,
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_USER_ID")] UserId = 3,
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_ORGANIZATION_ID")] OrganizationId = 4,
    [pbr::OriginalName("PERSONAL_ACCESS_TOKEN_FIELD_NAME_EXPIRATION_DATE")] ExpirationDate = 5,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PersonalAccessToken : pb::IMessage<PersonalAccessToken>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PersonalAccessToken> _parser = new pb::MessageParser<PersonalAccessToken>(() => new PersonalAccessToken());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PersonalAccessToken> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.User.V2.PatReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessToken() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessToken(PersonalAccessToken other) : this() {
      creationDate_ = other.creationDate_ != null ? other.creationDate_.Clone() : null;
      changeDate_ = other.changeDate_ != null ? other.changeDate_.Clone() : null;
      id_ = other.id_;
      userId_ = other.userId_;
      organizationId_ = other.organizationId_;
      expirationDate_ = other.expirationDate_ != null ? other.expirationDate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessToken Clone() {
      return new PersonalAccessToken(this);
    }

    /// <summary>Field number for the "creation_date" field.</summary>
    public const int CreationDateFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp creationDate_;
    /// <summary>
    /// The timestamp of the personal access token creation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreationDate {
      get { return creationDate_; }
      set {
        creationDate_ = value;
      }
    }

    /// <summary>Field number for the "change_date" field.</summary>
    public const int ChangeDateFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp changeDate_;
    /// <summary>
    /// The timestamp of the last change of the personal access token.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ChangeDate {
      get { return changeDate_; }
      set {
        changeDate_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 3;
    private string id_ = "";
    /// <summary>
    /// The unique identifier of the personal access token.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id" field.</summary>
    public const int UserIdFieldNumber = 4;
    private string userId_ = "";
    /// <summary>
    /// The unique identifier of the user the personal access token belongs to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserId {
      get { return userId_; }
      set {
        userId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "organization_id" field.</summary>
    public const int OrganizationIdFieldNumber = 5;
    private string organizationId_ = "";
    /// <summary>
    /// The unique identifier of the organization the personal access token belongs to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OrganizationId {
      get { return organizationId_; }
      set {
        organizationId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiration_date" field.</summary>
    public const int ExpirationDateFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expirationDate_;
    /// <summary>
    /// The personal access tokens expiration date.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ExpirationDate {
      get { return expirationDate_; }
      set {
        expirationDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PersonalAccessToken);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PersonalAccessToken other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(CreationDate, other.CreationDate)) return false;
      if (!object.Equals(ChangeDate, other.ChangeDate)) return false;
      if (Id != other.Id) return false;
      if (UserId != other.UserId) return false;
      if (OrganizationId != other.OrganizationId) return false;
      if (!object.Equals(ExpirationDate, other.ExpirationDate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (creationDate_ != null) hash ^= CreationDate.GetHashCode();
      if (changeDate_ != null) hash ^= ChangeDate.GetHashCode();
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (UserId.Length != 0) hash ^= UserId.GetHashCode();
      if (OrganizationId.Length != 0) hash ^= OrganizationId.GetHashCode();
      if (expirationDate_ != null) hash ^= ExpirationDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (creationDate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CreationDate);
      }
      if (changeDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangeDate);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Id);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OrganizationId);
      }
      if (expirationDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExpirationDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (creationDate_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(CreationDate);
      }
      if (changeDate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChangeDate);
      }
      if (Id.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Id);
      }
      if (UserId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(UserId);
      }
      if (OrganizationId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OrganizationId);
      }
      if (expirationDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExpirationDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (creationDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreationDate);
      }
      if (changeDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChangeDate);
      }
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (UserId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserId);
      }
      if (OrganizationId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrganizationId);
      }
      if (expirationDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpirationDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PersonalAccessToken other) {
      if (other == null) {
        return;
      }
      if (other.creationDate_ != null) {
        if (creationDate_ == null) {
          CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreationDate.MergeFrom(other.CreationDate);
      }
      if (other.changeDate_ != null) {
        if (changeDate_ == null) {
          ChangeDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ChangeDate.MergeFrom(other.ChangeDate);
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.UserId.Length != 0) {
        UserId = other.UserId;
      }
      if (other.OrganizationId.Length != 0) {
        OrganizationId = other.OrganizationId;
      }
      if (other.expirationDate_ != null) {
        if (expirationDate_ == null) {
          ExpirationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ExpirationDate.MergeFrom(other.ExpirationDate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (creationDate_ == null) {
              CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationDate);
            break;
          }
          case 18: {
            if (changeDate_ == null) {
              ChangeDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ChangeDate);
            break;
          }
          case 26: {
            Id = input.ReadString();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 42: {
            OrganizationId = input.ReadString();
            break;
          }
          case 50: {
            if (expirationDate_ == null) {
              ExpirationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpirationDate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (creationDate_ == null) {
              CreationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreationDate);
            break;
          }
          case 18: {
            if (changeDate_ == null) {
              ChangeDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ChangeDate);
            break;
          }
          case 26: {
            Id = input.ReadString();
            break;
          }
          case 34: {
            UserId = input.ReadString();
            break;
          }
          case 42: {
            OrganizationId = input.ReadString();
            break;
          }
          case 50: {
            if (expirationDate_ == null) {
              ExpirationDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpirationDate);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PersonalAccessTokensSearchFilter : pb::IMessage<PersonalAccessTokensSearchFilter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PersonalAccessTokensSearchFilter> _parser = new pb::MessageParser<PersonalAccessTokensSearchFilter>(() => new PersonalAccessTokensSearchFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PersonalAccessTokensSearchFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.User.V2.PatReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessTokensSearchFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessTokensSearchFilter(PersonalAccessTokensSearchFilter other) : this() {
      switch (other.FilterCase) {
        case FilterOneofCase.TokenIdFilter:
          TokenIdFilter = other.TokenIdFilter.Clone();
          break;
        case FilterOneofCase.UserIdFilter:
          UserIdFilter = other.UserIdFilter.Clone();
          break;
        case FilterOneofCase.OrganizationIdFilter:
          OrganizationIdFilter = other.OrganizationIdFilter.Clone();
          break;
        case FilterOneofCase.CreatedDateFilter:
          CreatedDateFilter = other.CreatedDateFilter.Clone();
          break;
        case FilterOneofCase.ExpirationDateFilter:
          ExpirationDateFilter = other.ExpirationDateFilter.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PersonalAccessTokensSearchFilter Clone() {
      return new PersonalAccessTokensSearchFilter(this);
    }

    /// <summary>Field number for the "token_id_filter" field.</summary>
    public const int TokenIdFilterFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Filter.V2.IDFilter TokenIdFilter {
      get { return filterCase_ == FilterOneofCase.TokenIdFilter ? (global::Zitadel.Filter.V2.IDFilter) filter_ : null; }
      set {
        filter_ = value;
        filterCase_ = value == null ? FilterOneofCase.None : FilterOneofCase.TokenIdFilter;
      }
    }

    /// <summary>Field number for the "user_id_filter" field.</summary>
    public const int UserIdFilterFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Filter.V2.IDFilter UserIdFilter {
      get { return filterCase_ == FilterOneofCase.UserIdFilter ? (global::Zitadel.Filter.V2.IDFilter) filter_ : null; }
      set {
        filter_ = value;
        filterCase_ = value == null ? FilterOneofCase.None : FilterOneofCase.UserIdFilter;
      }
    }

    /// <summary>Field number for the "organization_id_filter" field.</summary>
    public const int OrganizationIdFilterFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Filter.V2.IDFilter OrganizationIdFilter {
      get { return filterCase_ == FilterOneofCase.OrganizationIdFilter ? (global::Zitadel.Filter.V2.IDFilter) filter_ : null; }
      set {
        filter_ = value;
        filterCase_ = value == null ? FilterOneofCase.None : FilterOneofCase.OrganizationIdFilter;
      }
    }

    /// <summary>Field number for the "created_date_filter" field.</summary>
    public const int CreatedDateFilterFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Filter.V2.TimestampFilter CreatedDateFilter {
      get { return filterCase_ == FilterOneofCase.CreatedDateFilter ? (global::Zitadel.Filter.V2.TimestampFilter) filter_ : null; }
      set {
        filter_ = value;
        filterCase_ = value == null ? FilterOneofCase.None : FilterOneofCase.CreatedDateFilter;
      }
    }

    /// <summary>Field number for the "expiration_date_filter" field.</summary>
    public const int ExpirationDateFilterFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Filter.V2.TimestampFilter ExpirationDateFilter {
      get { return filterCase_ == FilterOneofCase.ExpirationDateFilter ? (global::Zitadel.Filter.V2.TimestampFilter) filter_ : null; }
      set {
        filter_ = value;
        filterCase_ = value == null ? FilterOneofCase.None : FilterOneofCase.ExpirationDateFilter;
      }
    }

    private object filter_;
    /// <summary>Enum of possible cases for the "filter" oneof.</summary>
    public enum FilterOneofCase {
      None = 0,
      TokenIdFilter = 1,
      UserIdFilter = 2,
      OrganizationIdFilter = 3,
      CreatedDateFilter = 4,
      ExpirationDateFilter = 5,
    }
    private FilterOneofCase filterCase_ = FilterOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public FilterOneofCase FilterCase {
      get { return filterCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFilter() {
      filterCase_ = FilterOneofCase.None;
      filter_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PersonalAccessTokensSearchFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PersonalAccessTokensSearchFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(TokenIdFilter, other.TokenIdFilter)) return false;
      if (!object.Equals(UserIdFilter, other.UserIdFilter)) return false;
      if (!object.Equals(OrganizationIdFilter, other.OrganizationIdFilter)) return false;
      if (!object.Equals(CreatedDateFilter, other.CreatedDateFilter)) return false;
      if (!object.Equals(ExpirationDateFilter, other.ExpirationDateFilter)) return false;
      if (FilterCase != other.FilterCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (filterCase_ == FilterOneofCase.TokenIdFilter) hash ^= TokenIdFilter.GetHashCode();
      if (filterCase_ == FilterOneofCase.UserIdFilter) hash ^= UserIdFilter.GetHashCode();
      if (filterCase_ == FilterOneofCase.OrganizationIdFilter) hash ^= OrganizationIdFilter.GetHashCode();
      if (filterCase_ == FilterOneofCase.CreatedDateFilter) hash ^= CreatedDateFilter.GetHashCode();
      if (filterCase_ == FilterOneofCase.ExpirationDateFilter) hash ^= ExpirationDateFilter.GetHashCode();
      hash ^= (int) filterCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (filterCase_ == FilterOneofCase.TokenIdFilter) {
        output.WriteRawTag(10);
        output.WriteMessage(TokenIdFilter);
      }
      if (filterCase_ == FilterOneofCase.UserIdFilter) {
        output.WriteRawTag(18);
        output.WriteMessage(UserIdFilter);
      }
      if (filterCase_ == FilterOneofCase.OrganizationIdFilter) {
        output.WriteRawTag(26);
        output.WriteMessage(OrganizationIdFilter);
      }
      if (filterCase_ == FilterOneofCase.CreatedDateFilter) {
        output.WriteRawTag(34);
        output.WriteMessage(CreatedDateFilter);
      }
      if (filterCase_ == FilterOneofCase.ExpirationDateFilter) {
        output.WriteRawTag(42);
        output.WriteMessage(ExpirationDateFilter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (filterCase_ == FilterOneofCase.TokenIdFilter) {
        output.WriteRawTag(10);
        output.WriteMessage(TokenIdFilter);
      }
      if (filterCase_ == FilterOneofCase.UserIdFilter) {
        output.WriteRawTag(18);
        output.WriteMessage(UserIdFilter);
      }
      if (filterCase_ == FilterOneofCase.OrganizationIdFilter) {
        output.WriteRawTag(26);
        output.WriteMessage(OrganizationIdFilter);
      }
      if (filterCase_ == FilterOneofCase.CreatedDateFilter) {
        output.WriteRawTag(34);
        output.WriteMessage(CreatedDateFilter);
      }
      if (filterCase_ == FilterOneofCase.ExpirationDateFilter) {
        output.WriteRawTag(42);
        output.WriteMessage(ExpirationDateFilter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (filterCase_ == FilterOneofCase.TokenIdFilter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TokenIdFilter);
      }
      if (filterCase_ == FilterOneofCase.UserIdFilter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UserIdFilter);
      }
      if (filterCase_ == FilterOneofCase.OrganizationIdFilter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrganizationIdFilter);
      }
      if (filterCase_ == FilterOneofCase.CreatedDateFilter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreatedDateFilter);
      }
      if (filterCase_ == FilterOneofCase.ExpirationDateFilter) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpirationDateFilter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PersonalAccessTokensSearchFilter other) {
      if (other == null) {
        return;
      }
      switch (other.FilterCase) {
        case FilterOneofCase.TokenIdFilter:
          if (TokenIdFilter == null) {
            TokenIdFilter = new global::Zitadel.Filter.V2.IDFilter();
          }
          TokenIdFilter.MergeFrom(other.TokenIdFilter);
          break;
        case FilterOneofCase.UserIdFilter:
          if (UserIdFilter == null) {
            UserIdFilter = new global::Zitadel.Filter.V2.IDFilter();
          }
          UserIdFilter.MergeFrom(other.UserIdFilter);
          break;
        case FilterOneofCase.OrganizationIdFilter:
          if (OrganizationIdFilter == null) {
            OrganizationIdFilter = new global::Zitadel.Filter.V2.IDFilter();
          }
          OrganizationIdFilter.MergeFrom(other.OrganizationIdFilter);
          break;
        case FilterOneofCase.CreatedDateFilter:
          if (CreatedDateFilter == null) {
            CreatedDateFilter = new global::Zitadel.Filter.V2.TimestampFilter();
          }
          CreatedDateFilter.MergeFrom(other.CreatedDateFilter);
          break;
        case FilterOneofCase.ExpirationDateFilter:
          if (ExpirationDateFilter == null) {
            ExpirationDateFilter = new global::Zitadel.Filter.V2.TimestampFilter();
          }
          ExpirationDateFilter.MergeFrom(other.ExpirationDateFilter);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.TokenIdFilter) {
              subBuilder.MergeFrom(TokenIdFilter);
            }
            input.ReadMessage(subBuilder);
            TokenIdFilter = subBuilder;
            break;
          }
          case 18: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.UserIdFilter) {
              subBuilder.MergeFrom(UserIdFilter);
            }
            input.ReadMessage(subBuilder);
            UserIdFilter = subBuilder;
            break;
          }
          case 26: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.OrganizationIdFilter) {
              subBuilder.MergeFrom(OrganizationIdFilter);
            }
            input.ReadMessage(subBuilder);
            OrganizationIdFilter = subBuilder;
            break;
          }
          case 34: {
            global::Zitadel.Filter.V2.TimestampFilter subBuilder = new global::Zitadel.Filter.V2.TimestampFilter();
            if (filterCase_ == FilterOneofCase.CreatedDateFilter) {
              subBuilder.MergeFrom(CreatedDateFilter);
            }
            input.ReadMessage(subBuilder);
            CreatedDateFilter = subBuilder;
            break;
          }
          case 42: {
            global::Zitadel.Filter.V2.TimestampFilter subBuilder = new global::Zitadel.Filter.V2.TimestampFilter();
            if (filterCase_ == FilterOneofCase.ExpirationDateFilter) {
              subBuilder.MergeFrom(ExpirationDateFilter);
            }
            input.ReadMessage(subBuilder);
            ExpirationDateFilter = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.TokenIdFilter) {
              subBuilder.MergeFrom(TokenIdFilter);
            }
            input.ReadMessage(subBuilder);
            TokenIdFilter = subBuilder;
            break;
          }
          case 18: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.UserIdFilter) {
              subBuilder.MergeFrom(UserIdFilter);
            }
            input.ReadMessage(subBuilder);
            UserIdFilter = subBuilder;
            break;
          }
          case 26: {
            global::Zitadel.Filter.V2.IDFilter subBuilder = new global::Zitadel.Filter.V2.IDFilter();
            if (filterCase_ == FilterOneofCase.OrganizationIdFilter) {
              subBuilder.MergeFrom(OrganizationIdFilter);
            }
            input.ReadMessage(subBuilder);
            OrganizationIdFilter = subBuilder;
            break;
          }
          case 34: {
            global::Zitadel.Filter.V2.TimestampFilter subBuilder = new global::Zitadel.Filter.V2.TimestampFilter();
            if (filterCase_ == FilterOneofCase.CreatedDateFilter) {
              subBuilder.MergeFrom(CreatedDateFilter);
            }
            input.ReadMessage(subBuilder);
            CreatedDateFilter = subBuilder;
            break;
          }
          case 42: {
            global::Zitadel.Filter.V2.TimestampFilter subBuilder = new global::Zitadel.Filter.V2.TimestampFilter();
            if (filterCase_ == FilterOneofCase.ExpirationDateFilter) {
              subBuilder.MergeFrom(ExpirationDateFilter);
            }
            input.ReadMessage(subBuilder);
            ExpirationDateFilter = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
