// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/application/v2/oidc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Application.V2 {

  /// <summary>Holder for reflection information generated from zitadel/application/v2/oidc.proto</summary>
  public static partial class OidcReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/application/v2/oidc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OidcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiF6aXRhZGVsL2FwcGxpY2F0aW9uL3YyL29pZGMucHJvdG8SFnppdGFkZWwu",
            "YXBwbGljYXRpb24udjIaHmdvb2dsZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90",
            "bxoucHJvdG9jLWdlbi1vcGVuYXBpdjIvb3B0aW9ucy9hbm5vdGF0aW9ucy5w",
            "cm90bxoXdmFsaWRhdGUvdmFsaWRhdGUucHJvdG8aInppdGFkZWwvYXBwbGlj",
            "YXRpb24vdjIvbG9naW4ucHJvdG8iVQoUT0lEQ0xvY2FsaXplZE1lc3NhZ2US",
            "EAoDa2V5GAEgASgJUgNrZXkSKwoRbG9jYWxpemVkX21lc3NhZ2UYAiABKAlS",
            "EGxvY2FsaXplZE1lc3NhZ2Ui3w0KEU9JRENDb25maWd1cmF0aW9uElYKDXJl",
            "ZGlyZWN0X3VyaXMYASADKAlCMZJBLkosWyJodHRwczovL2NvbnNvbGUueml0",
            "YWRlbC5jaC9hdXRoL2NhbGxiYWNrIl1SDHJlZGlyZWN0VXJpcxJPCg5yZXNw",
            "b25zZV90eXBlcxgCIAMoDjIoLnppdGFkZWwuYXBwbGljYXRpb24udjIuT0lE",
            "Q1Jlc3BvbnNlVHlwZVINcmVzcG9uc2VUeXBlcxJGCgtncmFudF90eXBlcxgD",
            "IAMoDjIlLnppdGFkZWwuYXBwbGljYXRpb24udjIuT0lEQ0dyYW50VHlwZVIK",
            "Z3JhbnRUeXBlcxKHAQoQYXBwbGljYXRpb25fdHlwZRgEIAEoDjIrLnppdGFk",
            "ZWwuYXBwbGljYXRpb24udjIuT0lEQ0FwcGxpY2F0aW9uVHlwZUIvkkEsMipk",
            "ZXRlcm1pbmVzIHRoZSBwYXJhZGlnbSBvZiB0aGUgYXBwbGljYXRpb25SD2Fw",
            "cGxpY2F0aW9uVHlwZRI9CgljbGllbnRfaWQYBSABKAlCIJJBHUobIjY5NjI5",
            "MDIzOTA2NDg4MzM0QFpJVEFERUwiUghjbGllbnRJZBJUChBhdXRoX21ldGhv",
            "ZF90eXBlGAYgASgOMioueml0YWRlbC5hcHBsaWNhdGlvbi52Mi5PSURDQXV0",
            "aE1ldGhvZFR5cGVSDmF1dGhNZXRob2RUeXBlEmUKGXBvc3RfbG9nb3V0X3Jl",
            "ZGlyZWN0X3VyaXMYByADKAlCKpJBJ0olWyJodHRwczovL2NvbnNvbGUueml0",
            "YWRlbC5jaC9sb2dvdXQiXVIWcG9zdExvZ291dFJlZGlyZWN0VXJpcxI9Cgd2",
            "ZXJzaW9uGAggASgOMiMueml0YWRlbC5hcHBsaWNhdGlvbi52Mi5PSURDVmVy",
            "c2lvblIHdmVyc2lvbhIjCg1ub25fY29tcGxpYW50GAkgASgIUgxub25Db21w",
            "bGlhbnQSXQoTY29tcGxpYW5jZV9wcm9ibGVtcxgKIAMoCzIsLnppdGFkZWwu",
            "YXBwbGljYXRpb24udjIuT0lEQ0xvY2FsaXplZE1lc3NhZ2VSEmNvbXBsaWFu",
            "Y2VQcm9ibGVtcxIpChBkZXZlbG9wbWVudF9tb2RlGAsgASgIUg9kZXZlbG9w",
            "bWVudE1vZGUSUQoRYWNjZXNzX3Rva2VuX3R5cGUYDCABKA4yJS56aXRhZGVs",
            "LmFwcGxpY2F0aW9uLnYyLk9JRENUb2tlblR5cGVSD2FjY2Vzc1Rva2VuVHlw",
            "ZRI9ChthY2Nlc3NfdG9rZW5fcm9sZV9hc3NlcnRpb24YDSABKAhSGGFjY2Vz",
            "c1Rva2VuUm9sZUFzc2VydGlvbhI1ChdpZF90b2tlbl9yb2xlX2Fzc2VydGlv",
            "bhgOIAEoCFIUaWRUb2tlblJvbGVBc3NlcnRpb24SPQobaWRfdG9rZW5fdXNl",
            "cmluZm9fYXNzZXJ0aW9uGA8gASgIUhhpZFRva2VuVXNlcmluZm9Bc3NlcnRp",
            "b24SOAoKY2xvY2tfc2tldxgQIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5EdXJh",
            "dGlvblIJY2xvY2tTa2V3EmAKEmFkZGl0aW9uYWxfb3JpZ2lucxgRIAMoCUIx",
            "kkEuSixbImh0dHBzOi8vY29uc29sZS56aXRhZGVsLmNoL2F1dGgvY2FsbGJh",
            "Y2siXVIRYWRkaXRpb25hbE9yaWdpbnMSTAoPYWxsb3dlZF9vcmlnaW5zGBIg",
            "AygJQiOSQSBKHlsiaHR0cHM6Ly9jb25zb2xlLnppdGFkZWwuY2giXVIOYWxs",
            "b3dlZE9yaWdpbnMSPgocc2tpcF9uYXRpdmVfYXBwX3N1Y2Nlc3NfcGFnZRgT",
            "IAEoCFIYc2tpcE5hdGl2ZUFwcFN1Y2Nlc3NQYWdlEmQKF2JhY2tfY2hhbm5l",
            "bF9sb2dvdXRfdXJpGBQgASgJQi2SQSpKKFsiaHR0cHM6Ly9leGFtcGxlLmNv",
            "bS9hdXRoL2JhY2tjaGFubmVsIl1SFGJhY2tDaGFubmVsTG9nb3V0VXJpEkkK",
            "DWxvZ2luX3ZlcnNpb24YFSABKAsyJC56aXRhZGVsLmFwcGxpY2F0aW9uLnYy",
            "LkxvZ2luVmVyc2lvblIMbG9naW5WZXJzaW9uEjoKA2lvcxgWIAEoCzIoLnpp",
            "dGFkZWwuYXBwbGljYXRpb24udjIuSU9TQXBwTGlua0NvbmZpZ1IDaW9zEkYK",
            "B2FuZHJvaWQYFyABKAsyLC56aXRhZGVsLmFwcGxpY2F0aW9uLnYyLkFuZHJv",
            "aWRBcHBMaW5rQ29uZmlnUgdhbmRyb2lkInEKEElPU0FwcExpbmtDb25maWcS",
            "MQoHdGVhbV9pZBgBIAEoCUIY+kIVchMyC15bQS1aMC05XSskmAEK0AEBUgZ0",
            "ZWFtSWQSKgoJYnVuZGxlX2lkGAIgASgJQg36QgpyCBABGMgB0AEBUghidW5k",
            "bGVJZCLJAQoUQW5kcm9pZEFwcExpbmtDb25maWcSMAoMcGFja2FnZV9uYW1l",
            "GAEgASgJQg36QgpyCBABGMgB0AEBUgtwYWNrYWdlTmFtZRJ/ChhzaGEyNTZf",
            "Y2VydF9maW5nZXJwcmludHMYAiADKAlCRfpCQpIBPxAUIjtyOTI3XihbMC05",
            "QS1GYS1mXXsyfSg6WzAtOUEtRmEtZl17Mn0pezMxfXxbMC05QS1GYS1mXXs2",
            "NH0pJFIWc2hhMjU2Q2VydEZpbmdlcnByaW50cyqbAQoQT0lEQ1Jlc3BvbnNl",
            "VHlwZRIiCh5PSURDX1JFU1BPTlNFX1RZUEVfVU5TUEVDSUZJRUQQABIbChdP",
            "SURDX1JFU1BPTlNFX1RZUEVfQ09ERRABEh8KG09JRENfUkVTUE9OU0VfVFlQ",
            "RV9JRF9UT0tFThACEiUKIU9JRENfUkVTUE9OU0VfVFlQRV9JRF9UT0tFTl9U",
            "T0tFThADKr0BCg1PSURDR3JhbnRUeXBlEiYKIk9JRENfR1JBTlRfVFlQRV9B",
            "VVRIT1JJWkFUSU9OX0NPREUQABIcChhPSURDX0dSQU5UX1RZUEVfSU1QTElD",
            "SVQQARIhCh1PSURDX0dSQU5UX1RZUEVfUkVGUkVTSF9UT0tFThACEh8KG09J",
            "RENfR1JBTlRfVFlQRV9ERVZJQ0VfQ09ERRADEiIKHk9JRENfR1JBTlRfVFlQ",
            "RV9UT0tFTl9FWENIQU5HRRAEKmQKE09JRENBcHBsaWNhdGlvblR5cGUSFQoR",
            "T0lEQ19BUFBfVFlQRV9XRUIQABIcChhPSURDX0FQUF9UWVBFX1VTRVJfQUdF",
            "TlQQARIYChRPSURDX0FQUF9UWVBFX05BVElWRRACKqABChJPSURDQXV0aE1l",
            "dGhvZFR5cGUSHwobT0lEQ19BVVRIX01FVEhPRF9UWVBFX0JBU0lDEAASHgoa",
            "T0lEQ19BVVRIX01FVEhPRF9UWVBFX1BPU1QQARIeChpPSURDX0FVVEhfTUVU",
            "SE9EX1RZUEVfTk9ORRACEikKJU9JRENfQVVUSF9NRVRIT0RfVFlQRV9QUklW",
            "QVRFX0tFWV9KV1QQAyojCgtPSURDVmVyc2lvbhIUChBPSURDX1ZFUlNJT05f",
            "MV8wEAAqRAoNT0lEQ1Rva2VuVHlwZRIaChZPSURDX1RPS0VOX1RZUEVfQkVB",
            "UkVSEAASFwoTT0lEQ19UT0tFTl9UWVBFX0pXVBABQuEBChpjb20ueml0YWRl",
            "bC5hcHBsaWNhdGlvbi52MkIJT2lkY1Byb3RvUAFaPmdpdGh1Yi5jb20veml0",
            "YWRlbC96aXRhZGVsL3BrZy9ncnBjL2FwcGxpY2F0aW9uL3YyO2FwcGxpY2F0",
            "aW9uogIDWkFYqgIWWml0YWRlbC5BcHBsaWNhdGlvbi5WMsoCFlppdGFkZWxc",
            "QXBwbGljYXRpb25cVjLiAiJaaXRhZGVsXEFwcGxpY2F0aW9uXFYyXEdQQk1l",
            "dGFkYXRh6gIYWml0YWRlbDo6QXBwbGljYXRpb246OlYyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Zitadel.Application.V2.LoginReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zitadel.Application.V2.OIDCResponseType), typeof(global::Zitadel.Application.V2.OIDCGrantType), typeof(global::Zitadel.Application.V2.OIDCApplicationType), typeof(global::Zitadel.Application.V2.OIDCAuthMethodType), typeof(global::Zitadel.Application.V2.OIDCVersion), typeof(global::Zitadel.Application.V2.OIDCTokenType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Application.V2.OIDCLocalizedMessage), global::Zitadel.Application.V2.OIDCLocalizedMessage.Parser, new[]{ "Key", "LocalizedMessage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Application.V2.OIDCConfiguration), global::Zitadel.Application.V2.OIDCConfiguration.Parser, new[]{ "RedirectUris", "ResponseTypes", "GrantTypes", "ApplicationType", "ClientId", "AuthMethodType", "PostLogoutRedirectUris", "Version", "NonCompliant", "ComplianceProblems", "DevelopmentMode", "AccessTokenType", "AccessTokenRoleAssertion", "IdTokenRoleAssertion", "IdTokenUserinfoAssertion", "ClockSkew", "AdditionalOrigins", "AllowedOrigins", "SkipNativeAppSuccessPage", "BackChannelLogoutUri", "LoginVersion", "Ios", "Android" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Application.V2.IOSAppLinkConfig), global::Zitadel.Application.V2.IOSAppLinkConfig.Parser, new[]{ "TeamId", "BundleId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Application.V2.AndroidAppLinkConfig), global::Zitadel.Application.V2.AndroidAppLinkConfig.Parser, new[]{ "PackageName", "Sha256CertFingerprints" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum OIDCResponseType {
    [pbr::OriginalName("OIDC_RESPONSE_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("OIDC_RESPONSE_TYPE_CODE")] Code = 1,
    [pbr::OriginalName("OIDC_RESPONSE_TYPE_ID_TOKEN")] IdToken = 2,
    [pbr::OriginalName("OIDC_RESPONSE_TYPE_ID_TOKEN_TOKEN")] IdTokenToken = 3,
  }

  public enum OIDCGrantType {
    [pbr::OriginalName("OIDC_GRANT_TYPE_AUTHORIZATION_CODE")] AuthorizationCode = 0,
    [pbr::OriginalName("OIDC_GRANT_TYPE_IMPLICIT")] Implicit = 1,
    [pbr::OriginalName("OIDC_GRANT_TYPE_REFRESH_TOKEN")] RefreshToken = 2,
    [pbr::OriginalName("OIDC_GRANT_TYPE_DEVICE_CODE")] DeviceCode = 3,
    [pbr::OriginalName("OIDC_GRANT_TYPE_TOKEN_EXCHANGE")] TokenExchange = 4,
  }

  public enum OIDCApplicationType {
    [pbr::OriginalName("OIDC_APP_TYPE_WEB")] OidcAppTypeWeb = 0,
    [pbr::OriginalName("OIDC_APP_TYPE_USER_AGENT")] OidcAppTypeUserAgent = 1,
    [pbr::OriginalName("OIDC_APP_TYPE_NATIVE")] OidcAppTypeNative = 2,
  }

  public enum OIDCAuthMethodType {
    [pbr::OriginalName("OIDC_AUTH_METHOD_TYPE_BASIC")] Basic = 0,
    [pbr::OriginalName("OIDC_AUTH_METHOD_TYPE_POST")] Post = 1,
    [pbr::OriginalName("OIDC_AUTH_METHOD_TYPE_NONE")] None = 2,
    [pbr::OriginalName("OIDC_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT")] PrivateKeyJwt = 3,
  }

  public enum OIDCVersion {
    [pbr::OriginalName("OIDC_VERSION_1_0")] _10 = 0,
  }

  public enum OIDCTokenType {
    [pbr::OriginalName("OIDC_TOKEN_TYPE_BEARER")] Bearer = 0,
    [pbr::OriginalName("OIDC_TOKEN_TYPE_JWT")] Jwt = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OIDCLocalizedMessage : pb::IMessage<OIDCLocalizedMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OIDCLocalizedMessage> _parser = new pb::MessageParser<OIDCLocalizedMessage>(() => new OIDCLocalizedMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OIDCLocalizedMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Application.V2.OidcReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCLocalizedMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCLocalizedMessage(OIDCLocalizedMessage other) : this() {
      key_ = other.key_;
      localizedMessage_ = other.localizedMessage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCLocalizedMessage Clone() {
      return new OIDCLocalizedMessage(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "localized_message" field.</summary>
    public const int LocalizedMessageFieldNumber = 2;
    private string localizedMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LocalizedMessage {
      get { return localizedMessage_; }
      set {
        localizedMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OIDCLocalizedMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OIDCLocalizedMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (LocalizedMessage != other.LocalizedMessage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (LocalizedMessage.Length != 0) hash ^= LocalizedMessage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (LocalizedMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LocalizedMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (LocalizedMessage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(LocalizedMessage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (LocalizedMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LocalizedMessage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OIDCLocalizedMessage other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.LocalizedMessage.Length != 0) {
        LocalizedMessage = other.LocalizedMessage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            LocalizedMessage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            LocalizedMessage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OIDCConfiguration : pb::IMessage<OIDCConfiguration>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OIDCConfiguration> _parser = new pb::MessageParser<OIDCConfiguration>(() => new OIDCConfiguration());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OIDCConfiguration> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Application.V2.OidcReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCConfiguration() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCConfiguration(OIDCConfiguration other) : this() {
      redirectUris_ = other.redirectUris_.Clone();
      responseTypes_ = other.responseTypes_.Clone();
      grantTypes_ = other.grantTypes_.Clone();
      applicationType_ = other.applicationType_;
      clientId_ = other.clientId_;
      authMethodType_ = other.authMethodType_;
      postLogoutRedirectUris_ = other.postLogoutRedirectUris_.Clone();
      version_ = other.version_;
      nonCompliant_ = other.nonCompliant_;
      complianceProblems_ = other.complianceProblems_.Clone();
      developmentMode_ = other.developmentMode_;
      accessTokenType_ = other.accessTokenType_;
      accessTokenRoleAssertion_ = other.accessTokenRoleAssertion_;
      idTokenRoleAssertion_ = other.idTokenRoleAssertion_;
      idTokenUserinfoAssertion_ = other.idTokenUserinfoAssertion_;
      clockSkew_ = other.clockSkew_ != null ? other.clockSkew_.Clone() : null;
      additionalOrigins_ = other.additionalOrigins_.Clone();
      allowedOrigins_ = other.allowedOrigins_.Clone();
      skipNativeAppSuccessPage_ = other.skipNativeAppSuccessPage_;
      backChannelLogoutUri_ = other.backChannelLogoutUri_;
      loginVersion_ = other.loginVersion_ != null ? other.loginVersion_.Clone() : null;
      ios_ = other.ios_ != null ? other.ios_.Clone() : null;
      android_ = other.android_ != null ? other.android_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OIDCConfiguration Clone() {
      return new OIDCConfiguration(this);
    }

    /// <summary>Field number for the "redirect_uris" field.</summary>
    public const int RedirectUrisFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_redirectUris_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> redirectUris_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// RedirectURIs are the allowed callback URIs for the OAuth2 / OIDC flows,
    /// where the authorization code or tokens will be sent to.
    /// The redirect_uri parameter in the authorization request must exactly match one of these URIs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RedirectUris {
      get { return redirectUris_; }
    }

    /// <summary>Field number for the "response_types" field.</summary>
    public const int ResponseTypesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Zitadel.Application.V2.OIDCResponseType> _repeated_responseTypes_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::Zitadel.Application.V2.OIDCResponseType) x);
    private readonly pbc::RepeatedField<global::Zitadel.Application.V2.OIDCResponseType> responseTypes_ = new pbc::RepeatedField<global::Zitadel.Application.V2.OIDCResponseType>();
    /// <summary>
    /// ResponseTypes define whether a code, id_token token or just id_token will be returned.
    /// The response_type parameter in the authorization request must exactly match one of these values.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zitadel.Application.V2.OIDCResponseType> ResponseTypes {
      get { return responseTypes_; }
    }

    /// <summary>Field number for the "grant_types" field.</summary>
    public const int GrantTypesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Zitadel.Application.V2.OIDCGrantType> _repeated_grantTypes_codec
        = pb::FieldCodec.ForEnum(26, x => (int) x, x => (global::Zitadel.Application.V2.OIDCGrantType) x);
    private readonly pbc::RepeatedField<global::Zitadel.Application.V2.OIDCGrantType> grantTypes_ = new pbc::RepeatedField<global::Zitadel.Application.V2.OIDCGrantType>();
    /// <summary>
    /// GrantTypes define the flow type the application is allowed to use.
    /// The grant_type parameter in the token request must exactly match one of these values.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zitadel.Application.V2.OIDCGrantType> GrantTypes {
      get { return grantTypes_; }
    }

    /// <summary>Field number for the "application_type" field.</summary>
    public const int ApplicationTypeFieldNumber = 4;
    private global::Zitadel.Application.V2.OIDCApplicationType applicationType_ = global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb;
    /// <summary>
    /// ApplicationType defines the OAuth2/OIDC client type and their ability to maintain
    /// confidentiality of their credentials.
    /// This influences the allowed grant types and the required authentication method.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.OIDCApplicationType ApplicationType {
      get { return applicationType_; }
      set {
        applicationType_ = value;
      }
    }

    /// <summary>Field number for the "client_id" field.</summary>
    public const int ClientIdFieldNumber = 5;
    private string clientId_ = "";
    /// <summary>
    /// The unique OAuth2/OIDC client_id used for authentication of the application,
    /// e.g. at the token endpoint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientId {
      get { return clientId_; }
      set {
        clientId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "auth_method_type" field.</summary>
    public const int AuthMethodTypeFieldNumber = 6;
    private global::Zitadel.Application.V2.OIDCAuthMethodType authMethodType_ = global::Zitadel.Application.V2.OIDCAuthMethodType.Basic;
    /// <summary>
    /// The authentication method type used by the application to authenticate at the token endpoint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.OIDCAuthMethodType AuthMethodType {
      get { return authMethodType_; }
      set {
        authMethodType_ = value;
      }
    }

    /// <summary>Field number for the "post_logout_redirect_uris" field.</summary>
    public const int PostLogoutRedirectUrisFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_postLogoutRedirectUris_codec
        = pb::FieldCodec.ForString(58);
    private readonly pbc::RepeatedField<string> postLogoutRedirectUris_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// PostLogoutRedirectURIs are the allowed URIs to redirect to after a logout.
    /// The post_logout_redirect_uri parameter in the logout request must exactly match one of these URIs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> PostLogoutRedirectUris {
      get { return postLogoutRedirectUris_; }
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 8;
    private global::Zitadel.Application.V2.OIDCVersion version_ = global::Zitadel.Application.V2.OIDCVersion._10;
    /// <summary>
    /// Version defines the OIDC version used by the application.
    /// Currently, only version 1.0 is supported.
    /// Future versions might introduce breaking changes.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.OIDCVersion Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "non_compliant" field.</summary>
    public const int NonCompliantFieldNumber = 9;
    private bool nonCompliant_;
    /// <summary>
    /// NonCompliant specifies whether the config is OIDC compliant. A production configuration SHOULD be compliant.
    /// Non-compliant configurations can run into interoperability issues with OIDC libraries and tools.
    /// Compliance problems are listed in the compliance_problems field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool NonCompliant {
      get { return nonCompliant_; }
      set {
        nonCompliant_ = value;
      }
    }

    /// <summary>Field number for the "compliance_problems" field.</summary>
    public const int ComplianceProblemsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Zitadel.Application.V2.OIDCLocalizedMessage> _repeated_complianceProblems_codec
        = pb::FieldCodec.ForMessage(82, global::Zitadel.Application.V2.OIDCLocalizedMessage.Parser);
    private readonly pbc::RepeatedField<global::Zitadel.Application.V2.OIDCLocalizedMessage> complianceProblems_ = new pbc::RepeatedField<global::Zitadel.Application.V2.OIDCLocalizedMessage>();
    /// <summary>
    /// ComplianceProblems lists the problems for non-compliant configurations.
    /// In case of a compliant configuration, this list is empty.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Zitadel.Application.V2.OIDCLocalizedMessage> ComplianceProblems {
      get { return complianceProblems_; }
    }

    /// <summary>Field number for the "development_mode" field.</summary>
    public const int DevelopmentModeFieldNumber = 11;
    private bool developmentMode_;
    /// <summary>
    /// DevelopmentMode can be enabled for development purposes. This allows the use of
    /// OIDC non-compliant and potentially insecure settings, such as the use of
    /// HTTP redirect URIs or wildcard redirect URIs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool DevelopmentMode {
      get { return developmentMode_; }
      set {
        developmentMode_ = value;
      }
    }

    /// <summary>Field number for the "access_token_type" field.</summary>
    public const int AccessTokenTypeFieldNumber = 12;
    private global::Zitadel.Application.V2.OIDCTokenType accessTokenType_ = global::Zitadel.Application.V2.OIDCTokenType.Bearer;
    /// <summary>
    /// The AccessTokenType defines the type of the access token returned from ZITADEL.
    /// Bearer tokens are opaque to clients. JWT tokens are self-contained and can be validated by the client.
    /// Bearer tokens must be introspected at the Zitadel token endpoint.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.OIDCTokenType AccessTokenType {
      get { return accessTokenType_; }
      set {
        accessTokenType_ = value;
      }
    }

    /// <summary>Field number for the "access_token_role_assertion" field.</summary>
    public const int AccessTokenRoleAssertionFieldNumber = 13;
    private bool accessTokenRoleAssertion_;
    /// <summary>
    /// If AccessTokenRoleAssertion is enabled, the roles of the user are added to the access token.
    /// Ensure that the access token is a JWT token and not a bearer token. And either request the roles
    /// by scope or enable the user role assertion on the project.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AccessTokenRoleAssertion {
      get { return accessTokenRoleAssertion_; }
      set {
        accessTokenRoleAssertion_ = value;
      }
    }

    /// <summary>Field number for the "id_token_role_assertion" field.</summary>
    public const int IdTokenRoleAssertionFieldNumber = 14;
    private bool idTokenRoleAssertion_;
    /// <summary>
    /// If IDTokenRoleAssertion is enabled, the roles of the user are added to the id token.
    /// Ensure that either the roles are requested by scope or enable the user role assertion on the
    /// project.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IdTokenRoleAssertion {
      get { return idTokenRoleAssertion_; }
      set {
        idTokenRoleAssertion_ = value;
      }
    }

    /// <summary>Field number for the "id_token_userinfo_assertion" field.</summary>
    public const int IdTokenUserinfoAssertionFieldNumber = 15;
    private bool idTokenUserinfoAssertion_;
    /// <summary>
    /// If IDTokenUserinfoAssertion is enabled, the claims of profile, email, address and phone scopes
    /// are added to the id token even if an access token is issued. This can be required by some applications
    /// that do not call the userinfo endpoint after authentication or directly use the id_token for retrieving
    /// user information.
    /// Attention: this violates the OIDC specification, which states that these claims must only be
    /// requested from the userinfo endpoint if an access token is issued. This is to prevent
    /// leaking of personal information in the id token, which is often stored in the browser and
    /// therefore more vulnerable.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IdTokenUserinfoAssertion {
      get { return idTokenUserinfoAssertion_; }
      set {
        idTokenUserinfoAssertion_ = value;
      }
    }

    /// <summary>Field number for the "clock_skew" field.</summary>
    public const int ClockSkewFieldNumber = 16;
    private global::Google.Protobuf.WellKnownTypes.Duration clockSkew_;
    /// <summary>
    /// ClockSkew is used to compensate time differences between the servers of Zitadel and the application.
    /// It is added to the "exp" claim and subtracted from "iat", "auth_time" and "nbf" claims.
    /// The default is 0s, the maximum is 5s.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration ClockSkew {
      get { return clockSkew_; }
      set {
        clockSkew_ = value;
      }
    }

    /// <summary>Field number for the "additional_origins" field.</summary>
    public const int AdditionalOriginsFieldNumber = 17;
    private static readonly pb::FieldCodec<string> _repeated_additionalOrigins_codec
        = pb::FieldCodec.ForString(138);
    private readonly pbc::RepeatedField<string> additionalOrigins_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// AdditionalOrigins are HTTP origins (scheme + host + port) from where the API can be used
    /// additional to the redirect_uris.
    /// This is useful if the application is used from an origin different to the redirect_uris,
    /// e.g. if the application is a SPA served in a native app, where the redirect_uri is a custom scheme,
    /// but the application is served from a https origin.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AdditionalOrigins {
      get { return additionalOrigins_; }
    }

    /// <summary>Field number for the "allowed_origins" field.</summary>
    public const int AllowedOriginsFieldNumber = 18;
    private static readonly pb::FieldCodec<string> _repeated_allowedOrigins_codec
        = pb::FieldCodec.ForString(146);
    private readonly pbc::RepeatedField<string> allowedOrigins_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// AllowedOrigins are all HTTP origins where the application is allowed to be used from.
    /// This is used to prevent CORS issues in browsers.
    /// If the origin of the request is not in this list, the request will be rejected.
    /// This is especially important for SPAs.
    /// Note that this is a generated list from the redirect_uris and additional_origins.
    /// If you use the application from another origin, you have to add it to the additional_origins.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> AllowedOrigins {
      get { return allowedOrigins_; }
    }

    /// <summary>Field number for the "skip_native_app_success_page" field.</summary>
    public const int SkipNativeAppSuccessPageFieldNumber = 19;
    private bool skipNativeAppSuccessPage_;
    /// <summary>
    /// For native apps a successful login usually shows a success page with a link to open the application again.
    /// SkipNativeAppSuccessPage can be used to skip this page and open the application directly.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool SkipNativeAppSuccessPage {
      get { return skipNativeAppSuccessPage_; }
      set {
        skipNativeAppSuccessPage_ = value;
      }
    }

    /// <summary>Field number for the "back_channel_logout_uri" field.</summary>
    public const int BackChannelLogoutUriFieldNumber = 20;
    private string backChannelLogoutUri_ = "";
    /// <summary>
    /// BackChannelLogoutURI is used to notify the application about terminated sessions according
    /// to the OIDC Back-Channel Logout (https://openid.net/specs/openid-connect-backchannel-1_0.html).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BackChannelLogoutUri {
      get { return backChannelLogoutUri_; }
      set {
        backChannelLogoutUri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "login_version" field.</summary>
    public const int LoginVersionFieldNumber = 21;
    private global::Zitadel.Application.V2.LoginVersion loginVersion_;
    /// <summary>
    /// LoginVersion specifies the login UI, where the user is redirected to for authentication.
    /// It can be used to select a specific login UI, e.g. for embedded UIs or for custom login pages
    /// hosted on any other domain.
    /// If unset, the login UI is chosen by the instance default.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.LoginVersion LoginVersion {
      get { return loginVersion_; }
      set {
        loginVersion_ = value;
      }
    }

    /// <summary>Field number for the "ios" field.</summary>
    public const int IosFieldNumber = 22;
    private global::Zitadel.Application.V2.IOSAppLinkConfig ios_;
    /// <summary>
    /// IOS is iOS Associated Domains / passkey trust config.
    /// Served in /.well-known/apple-app-site-association as webcredentials.apps entry
    /// "{team_id}.{bundle_id}" (Apple's full App ID = Team ID prefix + Bundle ID).
    /// Platform verifiers may cache the file; changes can take time to take effect.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.IOSAppLinkConfig Ios {
      get { return ios_; }
      set {
        ios_ = value;
      }
    }

    /// <summary>Field number for the "android" field.</summary>
    public const int AndroidFieldNumber = 23;
    private global::Zitadel.Application.V2.AndroidAppLinkConfig android_;
    /// <summary>
    /// Android is Android Digital Asset Links / passkey trust config.
    /// Served in /.well-known/assetlinks.json for delegate_permission/common.handle_all_urls and delegate_permission/common.get_login_creds.
    /// Platform verifiers may cache the file; changes can take time to take effect.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Application.V2.AndroidAppLinkConfig Android {
      get { return android_; }
      set {
        android_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OIDCConfiguration);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OIDCConfiguration other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!redirectUris_.Equals(other.redirectUris_)) return false;
      if(!responseTypes_.Equals(other.responseTypes_)) return false;
      if(!grantTypes_.Equals(other.grantTypes_)) return false;
      if (ApplicationType != other.ApplicationType) return false;
      if (ClientId != other.ClientId) return false;
      if (AuthMethodType != other.AuthMethodType) return false;
      if(!postLogoutRedirectUris_.Equals(other.postLogoutRedirectUris_)) return false;
      if (Version != other.Version) return false;
      if (NonCompliant != other.NonCompliant) return false;
      if(!complianceProblems_.Equals(other.complianceProblems_)) return false;
      if (DevelopmentMode != other.DevelopmentMode) return false;
      if (AccessTokenType != other.AccessTokenType) return false;
      if (AccessTokenRoleAssertion != other.AccessTokenRoleAssertion) return false;
      if (IdTokenRoleAssertion != other.IdTokenRoleAssertion) return false;
      if (IdTokenUserinfoAssertion != other.IdTokenUserinfoAssertion) return false;
      if (!object.Equals(ClockSkew, other.ClockSkew)) return false;
      if(!additionalOrigins_.Equals(other.additionalOrigins_)) return false;
      if(!allowedOrigins_.Equals(other.allowedOrigins_)) return false;
      if (SkipNativeAppSuccessPage != other.SkipNativeAppSuccessPage) return false;
      if (BackChannelLogoutUri != other.BackChannelLogoutUri) return false;
      if (!object.Equals(LoginVersion, other.LoginVersion)) return false;
      if (!object.Equals(Ios, other.Ios)) return false;
      if (!object.Equals(Android, other.Android)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= redirectUris_.GetHashCode();
      hash ^= responseTypes_.GetHashCode();
      hash ^= grantTypes_.GetHashCode();
      if (ApplicationType != global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb) hash ^= ApplicationType.GetHashCode();
      if (ClientId.Length != 0) hash ^= ClientId.GetHashCode();
      if (AuthMethodType != global::Zitadel.Application.V2.OIDCAuthMethodType.Basic) hash ^= AuthMethodType.GetHashCode();
      hash ^= postLogoutRedirectUris_.GetHashCode();
      if (Version != global::Zitadel.Application.V2.OIDCVersion._10) hash ^= Version.GetHashCode();
      if (NonCompliant != false) hash ^= NonCompliant.GetHashCode();
      hash ^= complianceProblems_.GetHashCode();
      if (DevelopmentMode != false) hash ^= DevelopmentMode.GetHashCode();
      if (AccessTokenType != global::Zitadel.Application.V2.OIDCTokenType.Bearer) hash ^= AccessTokenType.GetHashCode();
      if (AccessTokenRoleAssertion != false) hash ^= AccessTokenRoleAssertion.GetHashCode();
      if (IdTokenRoleAssertion != false) hash ^= IdTokenRoleAssertion.GetHashCode();
      if (IdTokenUserinfoAssertion != false) hash ^= IdTokenUserinfoAssertion.GetHashCode();
      if (clockSkew_ != null) hash ^= ClockSkew.GetHashCode();
      hash ^= additionalOrigins_.GetHashCode();
      hash ^= allowedOrigins_.GetHashCode();
      if (SkipNativeAppSuccessPage != false) hash ^= SkipNativeAppSuccessPage.GetHashCode();
      if (BackChannelLogoutUri.Length != 0) hash ^= BackChannelLogoutUri.GetHashCode();
      if (loginVersion_ != null) hash ^= LoginVersion.GetHashCode();
      if (ios_ != null) hash ^= Ios.GetHashCode();
      if (android_ != null) hash ^= Android.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      redirectUris_.WriteTo(output, _repeated_redirectUris_codec);
      responseTypes_.WriteTo(output, _repeated_responseTypes_codec);
      grantTypes_.WriteTo(output, _repeated_grantTypes_codec);
      if (ApplicationType != global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ApplicationType);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientId);
      }
      if (AuthMethodType != global::Zitadel.Application.V2.OIDCAuthMethodType.Basic) {
        output.WriteRawTag(48);
        output.WriteEnum((int) AuthMethodType);
      }
      postLogoutRedirectUris_.WriteTo(output, _repeated_postLogoutRedirectUris_codec);
      if (Version != global::Zitadel.Application.V2.OIDCVersion._10) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Version);
      }
      if (NonCompliant != false) {
        output.WriteRawTag(72);
        output.WriteBool(NonCompliant);
      }
      complianceProblems_.WriteTo(output, _repeated_complianceProblems_codec);
      if (DevelopmentMode != false) {
        output.WriteRawTag(88);
        output.WriteBool(DevelopmentMode);
      }
      if (AccessTokenType != global::Zitadel.Application.V2.OIDCTokenType.Bearer) {
        output.WriteRawTag(96);
        output.WriteEnum((int) AccessTokenType);
      }
      if (AccessTokenRoleAssertion != false) {
        output.WriteRawTag(104);
        output.WriteBool(AccessTokenRoleAssertion);
      }
      if (IdTokenRoleAssertion != false) {
        output.WriteRawTag(112);
        output.WriteBool(IdTokenRoleAssertion);
      }
      if (IdTokenUserinfoAssertion != false) {
        output.WriteRawTag(120);
        output.WriteBool(IdTokenUserinfoAssertion);
      }
      if (clockSkew_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(ClockSkew);
      }
      additionalOrigins_.WriteTo(output, _repeated_additionalOrigins_codec);
      allowedOrigins_.WriteTo(output, _repeated_allowedOrigins_codec);
      if (SkipNativeAppSuccessPage != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(SkipNativeAppSuccessPage);
      }
      if (BackChannelLogoutUri.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(BackChannelLogoutUri);
      }
      if (loginVersion_ != null) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(LoginVersion);
      }
      if (ios_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(Ios);
      }
      if (android_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(Android);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      redirectUris_.WriteTo(ref output, _repeated_redirectUris_codec);
      responseTypes_.WriteTo(ref output, _repeated_responseTypes_codec);
      grantTypes_.WriteTo(ref output, _repeated_grantTypes_codec);
      if (ApplicationType != global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ApplicationType);
      }
      if (ClientId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientId);
      }
      if (AuthMethodType != global::Zitadel.Application.V2.OIDCAuthMethodType.Basic) {
        output.WriteRawTag(48);
        output.WriteEnum((int) AuthMethodType);
      }
      postLogoutRedirectUris_.WriteTo(ref output, _repeated_postLogoutRedirectUris_codec);
      if (Version != global::Zitadel.Application.V2.OIDCVersion._10) {
        output.WriteRawTag(64);
        output.WriteEnum((int) Version);
      }
      if (NonCompliant != false) {
        output.WriteRawTag(72);
        output.WriteBool(NonCompliant);
      }
      complianceProblems_.WriteTo(ref output, _repeated_complianceProblems_codec);
      if (DevelopmentMode != false) {
        output.WriteRawTag(88);
        output.WriteBool(DevelopmentMode);
      }
      if (AccessTokenType != global::Zitadel.Application.V2.OIDCTokenType.Bearer) {
        output.WriteRawTag(96);
        output.WriteEnum((int) AccessTokenType);
      }
      if (AccessTokenRoleAssertion != false) {
        output.WriteRawTag(104);
        output.WriteBool(AccessTokenRoleAssertion);
      }
      if (IdTokenRoleAssertion != false) {
        output.WriteRawTag(112);
        output.WriteBool(IdTokenRoleAssertion);
      }
      if (IdTokenUserinfoAssertion != false) {
        output.WriteRawTag(120);
        output.WriteBool(IdTokenUserinfoAssertion);
      }
      if (clockSkew_ != null) {
        output.WriteRawTag(130, 1);
        output.WriteMessage(ClockSkew);
      }
      additionalOrigins_.WriteTo(ref output, _repeated_additionalOrigins_codec);
      allowedOrigins_.WriteTo(ref output, _repeated_allowedOrigins_codec);
      if (SkipNativeAppSuccessPage != false) {
        output.WriteRawTag(152, 1);
        output.WriteBool(SkipNativeAppSuccessPage);
      }
      if (BackChannelLogoutUri.Length != 0) {
        output.WriteRawTag(162, 1);
        output.WriteString(BackChannelLogoutUri);
      }
      if (loginVersion_ != null) {
        output.WriteRawTag(170, 1);
        output.WriteMessage(LoginVersion);
      }
      if (ios_ != null) {
        output.WriteRawTag(178, 1);
        output.WriteMessage(Ios);
      }
      if (android_ != null) {
        output.WriteRawTag(186, 1);
        output.WriteMessage(Android);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += redirectUris_.CalculateSize(_repeated_redirectUris_codec);
      size += responseTypes_.CalculateSize(_repeated_responseTypes_codec);
      size += grantTypes_.CalculateSize(_repeated_grantTypes_codec);
      if (ApplicationType != global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ApplicationType);
      }
      if (ClientId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientId);
      }
      if (AuthMethodType != global::Zitadel.Application.V2.OIDCAuthMethodType.Basic) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AuthMethodType);
      }
      size += postLogoutRedirectUris_.CalculateSize(_repeated_postLogoutRedirectUris_codec);
      if (Version != global::Zitadel.Application.V2.OIDCVersion._10) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Version);
      }
      if (NonCompliant != false) {
        size += 1 + 1;
      }
      size += complianceProblems_.CalculateSize(_repeated_complianceProblems_codec);
      if (DevelopmentMode != false) {
        size += 1 + 1;
      }
      if (AccessTokenType != global::Zitadel.Application.V2.OIDCTokenType.Bearer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) AccessTokenType);
      }
      if (AccessTokenRoleAssertion != false) {
        size += 1 + 1;
      }
      if (IdTokenRoleAssertion != false) {
        size += 1 + 1;
      }
      if (IdTokenUserinfoAssertion != false) {
        size += 1 + 1;
      }
      if (clockSkew_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ClockSkew);
      }
      size += additionalOrigins_.CalculateSize(_repeated_additionalOrigins_codec);
      size += allowedOrigins_.CalculateSize(_repeated_allowedOrigins_codec);
      if (SkipNativeAppSuccessPage != false) {
        size += 2 + 1;
      }
      if (BackChannelLogoutUri.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(BackChannelLogoutUri);
      }
      if (loginVersion_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(LoginVersion);
      }
      if (ios_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Ios);
      }
      if (android_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Android);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OIDCConfiguration other) {
      if (other == null) {
        return;
      }
      redirectUris_.Add(other.redirectUris_);
      responseTypes_.Add(other.responseTypes_);
      grantTypes_.Add(other.grantTypes_);
      if (other.ApplicationType != global::Zitadel.Application.V2.OIDCApplicationType.OidcAppTypeWeb) {
        ApplicationType = other.ApplicationType;
      }
      if (other.ClientId.Length != 0) {
        ClientId = other.ClientId;
      }
      if (other.AuthMethodType != global::Zitadel.Application.V2.OIDCAuthMethodType.Basic) {
        AuthMethodType = other.AuthMethodType;
      }
      postLogoutRedirectUris_.Add(other.postLogoutRedirectUris_);
      if (other.Version != global::Zitadel.Application.V2.OIDCVersion._10) {
        Version = other.Version;
      }
      if (other.NonCompliant != false) {
        NonCompliant = other.NonCompliant;
      }
      complianceProblems_.Add(other.complianceProblems_);
      if (other.DevelopmentMode != false) {
        DevelopmentMode = other.DevelopmentMode;
      }
      if (other.AccessTokenType != global::Zitadel.Application.V2.OIDCTokenType.Bearer) {
        AccessTokenType = other.AccessTokenType;
      }
      if (other.AccessTokenRoleAssertion != false) {
        AccessTokenRoleAssertion = other.AccessTokenRoleAssertion;
      }
      if (other.IdTokenRoleAssertion != false) {
        IdTokenRoleAssertion = other.IdTokenRoleAssertion;
      }
      if (other.IdTokenUserinfoAssertion != false) {
        IdTokenUserinfoAssertion = other.IdTokenUserinfoAssertion;
      }
      if (other.clockSkew_ != null) {
        if (clockSkew_ == null) {
          ClockSkew = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        ClockSkew.MergeFrom(other.ClockSkew);
      }
      additionalOrigins_.Add(other.additionalOrigins_);
      allowedOrigins_.Add(other.allowedOrigins_);
      if (other.SkipNativeAppSuccessPage != false) {
        SkipNativeAppSuccessPage = other.SkipNativeAppSuccessPage;
      }
      if (other.BackChannelLogoutUri.Length != 0) {
        BackChannelLogoutUri = other.BackChannelLogoutUri;
      }
      if (other.loginVersion_ != null) {
        if (loginVersion_ == null) {
          LoginVersion = new global::Zitadel.Application.V2.LoginVersion();
        }
        LoginVersion.MergeFrom(other.LoginVersion);
      }
      if (other.ios_ != null) {
        if (ios_ == null) {
          Ios = new global::Zitadel.Application.V2.IOSAppLinkConfig();
        }
        Ios.MergeFrom(other.Ios);
      }
      if (other.android_ != null) {
        if (android_ == null) {
          Android = new global::Zitadel.Application.V2.AndroidAppLinkConfig();
        }
        Android.MergeFrom(other.Android);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            redirectUris_.AddEntriesFrom(input, _repeated_redirectUris_codec);
            break;
          }
          case 18:
          case 16: {
            responseTypes_.AddEntriesFrom(input, _repeated_responseTypes_codec);
            break;
          }
          case 26:
          case 24: {
            grantTypes_.AddEntriesFrom(input, _repeated_grantTypes_codec);
            break;
          }
          case 32: {
            ApplicationType = (global::Zitadel.Application.V2.OIDCApplicationType) input.ReadEnum();
            break;
          }
          case 42: {
            ClientId = input.ReadString();
            break;
          }
          case 48: {
            AuthMethodType = (global::Zitadel.Application.V2.OIDCAuthMethodType) input.ReadEnum();
            break;
          }
          case 58: {
            postLogoutRedirectUris_.AddEntriesFrom(input, _repeated_postLogoutRedirectUris_codec);
            break;
          }
          case 64: {
            Version = (global::Zitadel.Application.V2.OIDCVersion) input.ReadEnum();
            break;
          }
          case 72: {
            NonCompliant = input.ReadBool();
            break;
          }
          case 82: {
            complianceProblems_.AddEntriesFrom(input, _repeated_complianceProblems_codec);
            break;
          }
          case 88: {
            DevelopmentMode = input.ReadBool();
            break;
          }
          case 96: {
            AccessTokenType = (global::Zitadel.Application.V2.OIDCTokenType) input.ReadEnum();
            break;
          }
          case 104: {
            AccessTokenRoleAssertion = input.ReadBool();
            break;
          }
          case 112: {
            IdTokenRoleAssertion = input.ReadBool();
            break;
          }
          case 120: {
            IdTokenUserinfoAssertion = input.ReadBool();
            break;
          }
          case 130: {
            if (clockSkew_ == null) {
              ClockSkew = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(ClockSkew);
            break;
          }
          case 138: {
            additionalOrigins_.AddEntriesFrom(input, _repeated_additionalOrigins_codec);
            break;
          }
          case 146: {
            allowedOrigins_.AddEntriesFrom(input, _repeated_allowedOrigins_codec);
            break;
          }
          case 152: {
            SkipNativeAppSuccessPage = input.ReadBool();
            break;
          }
          case 162: {
            BackChannelLogoutUri = input.ReadString();
            break;
          }
          case 170: {
            if (loginVersion_ == null) {
              LoginVersion = new global::Zitadel.Application.V2.LoginVersion();
            }
            input.ReadMessage(LoginVersion);
            break;
          }
          case 178: {
            if (ios_ == null) {
              Ios = new global::Zitadel.Application.V2.IOSAppLinkConfig();
            }
            input.ReadMessage(Ios);
            break;
          }
          case 186: {
            if (android_ == null) {
              Android = new global::Zitadel.Application.V2.AndroidAppLinkConfig();
            }
            input.ReadMessage(Android);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            redirectUris_.AddEntriesFrom(ref input, _repeated_redirectUris_codec);
            break;
          }
          case 18:
          case 16: {
            responseTypes_.AddEntriesFrom(ref input, _repeated_responseTypes_codec);
            break;
          }
          case 26:
          case 24: {
            grantTypes_.AddEntriesFrom(ref input, _repeated_grantTypes_codec);
            break;
          }
          case 32: {
            ApplicationType = (global::Zitadel.Application.V2.OIDCApplicationType) input.ReadEnum();
            break;
          }
          case 42: {
            ClientId = input.ReadString();
            break;
          }
          case 48: {
            AuthMethodType = (global::Zitadel.Application.V2.OIDCAuthMethodType) input.ReadEnum();
            break;
          }
          case 58: {
            postLogoutRedirectUris_.AddEntriesFrom(ref input, _repeated_postLogoutRedirectUris_codec);
            break;
          }
          case 64: {
            Version = (global::Zitadel.Application.V2.OIDCVersion) input.ReadEnum();
            break;
          }
          case 72: {
            NonCompliant = input.ReadBool();
            break;
          }
          case 82: {
            complianceProblems_.AddEntriesFrom(ref input, _repeated_complianceProblems_codec);
            break;
          }
          case 88: {
            DevelopmentMode = input.ReadBool();
            break;
          }
          case 96: {
            AccessTokenType = (global::Zitadel.Application.V2.OIDCTokenType) input.ReadEnum();
            break;
          }
          case 104: {
            AccessTokenRoleAssertion = input.ReadBool();
            break;
          }
          case 112: {
            IdTokenRoleAssertion = input.ReadBool();
            break;
          }
          case 120: {
            IdTokenUserinfoAssertion = input.ReadBool();
            break;
          }
          case 130: {
            if (clockSkew_ == null) {
              ClockSkew = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(ClockSkew);
            break;
          }
          case 138: {
            additionalOrigins_.AddEntriesFrom(ref input, _repeated_additionalOrigins_codec);
            break;
          }
          case 146: {
            allowedOrigins_.AddEntriesFrom(ref input, _repeated_allowedOrigins_codec);
            break;
          }
          case 152: {
            SkipNativeAppSuccessPage = input.ReadBool();
            break;
          }
          case 162: {
            BackChannelLogoutUri = input.ReadString();
            break;
          }
          case 170: {
            if (loginVersion_ == null) {
              LoginVersion = new global::Zitadel.Application.V2.LoginVersion();
            }
            input.ReadMessage(LoginVersion);
            break;
          }
          case 178: {
            if (ios_ == null) {
              Ios = new global::Zitadel.Application.V2.IOSAppLinkConfig();
            }
            input.ReadMessage(Ios);
            break;
          }
          case 186: {
            if (android_ == null) {
              Android = new global::Zitadel.Application.V2.AndroidAppLinkConfig();
            }
            input.ReadMessage(Android);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// IOSAppLinkConfig is iOS Associated Domains / passkey trust config.
  /// Served in /.well-known/apple-app-site-association as webcredentials.apps entry
  /// "{team_id}.{bundle_id}" (Apple's full App ID = Team ID prefix + Bundle ID).
  /// Platform verifiers may cache the file; changes can take time to take effect.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IOSAppLinkConfig : pb::IMessage<IOSAppLinkConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IOSAppLinkConfig> _parser = new pb::MessageParser<IOSAppLinkConfig>(() => new IOSAppLinkConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IOSAppLinkConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Application.V2.OidcReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IOSAppLinkConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IOSAppLinkConfig(IOSAppLinkConfig other) : this() {
      teamId_ = other.teamId_;
      bundleId_ = other.bundleId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IOSAppLinkConfig Clone() {
      return new IOSAppLinkConfig(this);
    }

    /// <summary>Field number for the "team_id" field.</summary>
    public const int TeamIdFieldNumber = 1;
    private string teamId_ = "";
    /// <summary>
    /// TeamID is the Apple Developer Team ID (exactly 10 alphanumeric characters), e.g. ABCDE12345.
    /// From Apple Developer account membership — not the Bundle ID.
    /// Empty clears the value on update.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TeamId {
      get { return teamId_; }
      set {
        teamId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bundle_id" field.</summary>
    public const int BundleIdFieldNumber = 2;
    private string bundleId_ = "";
    /// <summary>
    /// BundleID is the Xcode / CFBundleIdentifier, e.g. com.example.app.
    /// Not the full Apple App ID; do not include the Team ID prefix here.
    /// Empty clears the value on update.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BundleId {
      get { return bundleId_; }
      set {
        bundleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IOSAppLinkConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IOSAppLinkConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TeamId != other.TeamId) return false;
      if (BundleId != other.BundleId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TeamId.Length != 0) hash ^= TeamId.GetHashCode();
      if (BundleId.Length != 0) hash ^= BundleId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TeamId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TeamId);
      }
      if (BundleId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TeamId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TeamId);
      }
      if (BundleId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BundleId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TeamId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TeamId);
      }
      if (BundleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BundleId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IOSAppLinkConfig other) {
      if (other == null) {
        return;
      }
      if (other.TeamId.Length != 0) {
        TeamId = other.TeamId;
      }
      if (other.BundleId.Length != 0) {
        BundleId = other.BundleId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TeamId = input.ReadString();
            break;
          }
          case 18: {
            BundleId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TeamId = input.ReadString();
            break;
          }
          case 18: {
            BundleId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// AndroidAppLinkConfig is Android Digital Asset Links / passkey trust config.
  /// Served in /.well-known/assetlinks.json for delegate_permission/common.handle_all_urls and delegate_permission/common.get_login_creds.
  /// Platform verifiers may cache the file; changes can take time to take effect.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AndroidAppLinkConfig : pb::IMessage<AndroidAppLinkConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AndroidAppLinkConfig> _parser = new pb::MessageParser<AndroidAppLinkConfig>(() => new AndroidAppLinkConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AndroidAppLinkConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Application.V2.OidcReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidAppLinkConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidAppLinkConfig(AndroidAppLinkConfig other) : this() {
      packageName_ = other.packageName_;
      sha256CertFingerprints_ = other.sha256CertFingerprints_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AndroidAppLinkConfig Clone() {
      return new AndroidAppLinkConfig(this);
    }

    /// <summary>Field number for the "package_name" field.</summary>
    public const int PackageNameFieldNumber = 1;
    private string packageName_ = "";
    /// <summary>
    /// PackageName is the Android applicationId / package name from the app manifest.
    /// Empty clears the value on update.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PackageName {
      get { return packageName_; }
      set {
        packageName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sha256_cert_fingerprints" field.</summary>
    public const int Sha256CertFingerprintsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_sha256CertFingerprints_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> sha256CertFingerprints_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// SHA256CertFingerprints are signing certificate fingerprints (64 hex chars, optional colons).
    /// Include debug and release fingerprints as needed. At most 20 entries.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Sha256CertFingerprints {
      get { return sha256CertFingerprints_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AndroidAppLinkConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AndroidAppLinkConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PackageName != other.PackageName) return false;
      if(!sha256CertFingerprints_.Equals(other.sha256CertFingerprints_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PackageName.Length != 0) hash ^= PackageName.GetHashCode();
      hash ^= sha256CertFingerprints_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PackageName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PackageName);
      }
      sha256CertFingerprints_.WriteTo(output, _repeated_sha256CertFingerprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PackageName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PackageName);
      }
      sha256CertFingerprints_.WriteTo(ref output, _repeated_sha256CertFingerprints_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PackageName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PackageName);
      }
      size += sha256CertFingerprints_.CalculateSize(_repeated_sha256CertFingerprints_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AndroidAppLinkConfig other) {
      if (other == null) {
        return;
      }
      if (other.PackageName.Length != 0) {
        PackageName = other.PackageName;
      }
      sha256CertFingerprints_.Add(other.sha256CertFingerprints_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PackageName = input.ReadString();
            break;
          }
          case 18: {
            sha256CertFingerprints_.AddEntriesFrom(input, _repeated_sha256CertFingerprints_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            PackageName = input.ReadString();
            break;
          }
          case 18: {
            sha256CertFingerprints_.AddEntriesFrom(ref input, _repeated_sha256CertFingerprints_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
