// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/session/v2/challenge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Session.V2 {

  /// <summary>Holder for reflection information generated from zitadel/session/v2/challenge.proto</summary>
  public static partial class ChallengeReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/session/v2/challenge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChallengeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJ6aXRhZGVsL3Nlc3Npb24vdjIvY2hhbGxlbmdlLnByb3RvEhJ6aXRhZGVs",
            "LnNlc3Npb24udjIaH2dvb2dsZS9hcGkvZmllbGRfYmVoYXZpb3IucHJvdG8a",
            "HGdvb2dsZS9wcm90b2J1Zi9zdHJ1Y3QucHJvdG8aLnByb3RvYy1nZW4tb3Bl",
            "bmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJvdG8aF3ZhbGlkYXRlL3Zh",
            "bGlkYXRlLnByb3RvIukJChFSZXF1ZXN0Q2hhbGxlbmdlcxJRCgp3ZWJfYXV0",
            "aF9uGAEgASgLMi4ueml0YWRlbC5zZXNzaW9uLnYyLlJlcXVlc3RDaGFsbGVu",
            "Z2VzLldlYkF1dGhOSABSCHdlYkF1dGhOiAEBEkoKB290cF9zbXMYAiABKAsy",
            "LC56aXRhZGVsLnNlc3Npb24udjIuUmVxdWVzdENoYWxsZW5nZXMuT1RQU01T",
            "SAFSBm90cFNtc4gBARJQCglvdHBfZW1haWwYAyABKAsyLi56aXRhZGVsLnNl",
            "c3Npb24udjIuUmVxdWVzdENoYWxsZW5nZXMuT1RQRW1haWxIAlIIb3RwRW1h",
            "aWyIAQEajQQKCFdlYkF1dGhOEn0KBmRvbWFpbhgBIAEoCUJlkkFUMlIiRG9t",
            "YWluIG9uIHdoaWNoIHRoZSBzZXNzaW9uIHdhcyBjcmVhdGVkLiBXaWxsIGJl",
            "IHVzZWQgaW4gdGhlIFdlYkF1dGhOIGNoYWxsZW5nZS4i4kEBAvpCB3IFEAEY",
            "yAFSBmRvbWFpbhKBAwoddXNlcl92ZXJpZmljYXRpb25fcmVxdWlyZW1lbnQY",
            "AiABKA4yLy56aXRhZGVsLnNlc3Npb24udjIuVXNlclZlcmlmaWNhdGlvblJl",
            "cXVpcmVtZW50QosCkkH5ARpAaHR0cHM6Ly93d3cudzMub3JnL1RSL3dlYmF1",
            "dGhuLyNlbnVtLXVzZXJWZXJpZmljYXRpb25SZXF1aXJlbWVudDK0ASJVc2Vy",
            "IHZlcmlmaWNhdGlvbiB0aGF0IGlzIHJlcXVpcmVkIGR1cmluZyB2YWxpZGF0",
            "aW9uLiBXaGVuIHNldCB0byBgVVNFUl9WRVJJRklDQVRJT05fUkVRVUlSRU1F",
            "TlRfUkVRVUlSRURgIHRoZSBiZWhhdmlvdXIgaXMgZm9yIHBhc3NrZXkgYXV0",
            "aGVudGljYXRpb24uIE90aGVyIHZhbHVlcyB3aWxsIG1lYW4gVTJGIuJBAQL6",
            "QgeCAQQQASAAUht1c2VyVmVyaWZpY2F0aW9uUmVxdWlyZW1lbnQaKQoGT1RQ",
            "U01TEh8KC3JldHVybl9jb2RlGAEgASgIUgpyZXR1cm5Db2RlGv4CCghPVFBF",
            "bWFpbBJWCglzZW5kX2NvZGUYAiABKAsyNy56aXRhZGVsLnNlc3Npb24udjIu",
            "UmVxdWVzdENoYWxsZW5nZXMuT1RQRW1haWwuU2VuZENvZGVIAFIIc2VuZENv",
            "ZGUSXAoLcmV0dXJuX2NvZGUYAyABKAsyOS56aXRhZGVsLnNlc3Npb24udjIu",
            "UmVxdWVzdENoYWxsZW5nZXMuT1RQRW1haWwuUmV0dXJuQ29kZUgAUgpyZXR1",
            "cm5Db2RlGpwBCghTZW5kQ29kZRJ/Cgx1cmxfdGVtcGxhdGUYASABKAlCV5JB",
            "SkpCImh0dHBzOi8vZXhhbXBsZS5jb20vb3RwL3ZlcmlmeT91c2VySUQ9e3su",
            "VXNlcklEfX0mY29kZT17ey5Db2RlfX0ieMgBgAEB+kIHcgUQARjIAUgAUgt1",
            "cmxUZW1wbGF0ZYgBAUIPCg1fdXJsX3RlbXBsYXRlGgwKClJldHVybkNvZGVC",
            "DwoNZGVsaXZlcnlfdHlwZUINCgtfd2ViX2F1dGhfbkIKCghfb3RwX3Ntc0IM",
            "Cgpfb3RwX2VtYWlsIqoGCgpDaGFsbGVuZ2VzEkoKCndlYl9hdXRoX24YASAB",
            "KAsyJy56aXRhZGVsLnNlc3Npb24udjIuQ2hhbGxlbmdlcy5XZWJBdXRoTkgA",
            "Ugh3ZWJBdXRoTogBARIcCgdvdHBfc21zGAIgASgJSAFSBm90cFNtc4gBARIg",
            "CglvdHBfZW1haWwYAyABKAlIAlIIb3RwRW1haWyIAQEa5gQKCFdlYkF1dGhO",
            "EtkECiVwdWJsaWNfa2V5X2NyZWRlbnRpYWxfcmVxdWVzdF9vcHRpb25zGAEg",
            "ASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdELtA5JB6QMy+gFPcHRpb25z",
            "IGZvciBBc3NlcnRpb24gR2VuZXJhcmF0aW9uIChkaWN0aW9uYXJ5IFB1Ymxp",
            "Y0tleUNyZWRlbnRpYWxSZXF1ZXN0T3B0aW9ucykuIEdlbmVyYXRlZCBoZWxw",
            "ZXIgbWV0aG9kcyB0cmFuc2Zvcm0gdGhlIGZpZWxkIHRvIEpTT04sIGZvciB1",
            "c2UgaW4gYSBXZWJhdXRoTiBjbGllbnQuIFNlZSBhbHNvOiBodHRwczovL3d3",
            "dy53My5vcmcvVFIvd2ViYXV0aG4vI2RpY3RkZWYtcHVibGlja2V5Y3JlZGVu",
            "dGlhbHJlcXVlc3RvcHRpb25zSukBeyJwdWJsaWNLZXkiOnsiYWxsb3dDcmVk",
            "ZW50aWFscyI6W3siaWQiOiJBVG1xQmctOTlxeU9aazJ6bG9QZEpReVMyUjdJ",
            "a0ZUN3Y5SG9vc19CX25NIiwidHlwZSI6InB1YmxpYy1rZXkifV0sImNoYWxs",
            "ZW5nZSI6IkdBT0hZejJqRTY5a0pNWW82TGFpajh5V3c5LWRLS2diVmlOaGZ1",
            "eTBTdEEiLCJycElkIjoibG9jYWxob3N0IiwidGltZW91dCI6MzAwMDAwLCJ1",
            "c2VyVmVyaWZpY2F0aW9uIjoicmVxdWlyZWQifX1SIXB1YmxpY0tleUNyZWRl",
            "bnRpYWxSZXF1ZXN0T3B0aW9uc0INCgtfd2ViX2F1dGhfbkIKCghfb3RwX3Nt",
            "c0IMCgpfb3RwX2VtYWlsKtQBChtVc2VyVmVyaWZpY2F0aW9uUmVxdWlyZW1l",
            "bnQSLQopVVNFUl9WRVJJRklDQVRJT05fUkVRVUlSRU1FTlRfVU5TUEVDSUZJ",
            "RUQQABIqCiZVU0VSX1ZFUklGSUNBVElPTl9SRVFVSVJFTUVOVF9SRVFVSVJF",
            "RBABEisKJ1VTRVJfVkVSSUZJQ0FUSU9OX1JFUVVJUkVNRU5UX1BSRUZFUlJF",
            "RBACEi0KKVVTRVJfVkVSSUZJQ0FUSU9OX1JFUVVJUkVNRU5UX0RJU0NPVVJB",
            "R0VEEANCygEKFmNvbS56aXRhZGVsLnNlc3Npb24udjJCDkNoYWxsZW5nZVBy",
            "b3RvUAFaNmdpdGh1Yi5jb20veml0YWRlbC96aXRhZGVsL3BrZy9ncnBjL3Nl",
            "c3Npb24vdjI7c2Vzc2lvbqICA1pTWKoCElppdGFkZWwuU2Vzc2lvbi5WMsoC",
            "ElppdGFkZWxcU2Vzc2lvblxWMuICHlppdGFkZWxcU2Vzc2lvblxWMlxHUEJN",
            "ZXRhZGF0YeoCFFppdGFkZWw6OlNlc3Npb246OlYyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.FieldBehaviorReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.StructReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zitadel.Session.V2.UserVerificationRequirement), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges), global::Zitadel.Session.V2.RequestChallenges.Parser, new[]{ "WebAuthN", "OtpSms", "OtpEmail" }, new[]{ "WebAuthN", "OtpSms", "OtpEmail" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN), global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN.Parser, new[]{ "Domain", "UserVerificationRequirement" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS), global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS.Parser, new[]{ "ReturnCode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail), global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Parser, new[]{ "SendCode", "ReturnCode" }, new[]{ "DeliveryType" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode), global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode.Parser, new[]{ "UrlTemplate" }, new[]{ "UrlTemplate" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode), global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode.Parser, null, null, null, null, null)})}),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.Challenges), global::Zitadel.Session.V2.Challenges.Parser, new[]{ "WebAuthN", "OtpSms", "OtpEmail" }, new[]{ "WebAuthN", "OtpSms", "OtpEmail" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Session.V2.Challenges.Types.WebAuthN), global::Zitadel.Session.V2.Challenges.Types.WebAuthN.Parser, new[]{ "PublicKeyCredentialRequestOptions" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum UserVerificationRequirement {
    [pbr::OriginalName("USER_VERIFICATION_REQUIREMENT_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("USER_VERIFICATION_REQUIREMENT_REQUIRED")] Required = 1,
    [pbr::OriginalName("USER_VERIFICATION_REQUIREMENT_PREFERRED")] Preferred = 2,
    [pbr::OriginalName("USER_VERIFICATION_REQUIREMENT_DISCOURAGED")] Discouraged = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RequestChallenges : pb::IMessage<RequestChallenges>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RequestChallenges> _parser = new pb::MessageParser<RequestChallenges>(() => new RequestChallenges());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RequestChallenges> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Session.V2.ChallengeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestChallenges() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestChallenges(RequestChallenges other) : this() {
      webAuthN_ = other.webAuthN_ != null ? other.webAuthN_.Clone() : null;
      otpSms_ = other.otpSms_ != null ? other.otpSms_.Clone() : null;
      otpEmail_ = other.otpEmail_ != null ? other.otpEmail_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestChallenges Clone() {
      return new RequestChallenges(this);
    }

    /// <summary>Field number for the "web_auth_n" field.</summary>
    public const int WebAuthNFieldNumber = 1;
    private global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN webAuthN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN WebAuthN {
      get { return webAuthN_; }
      set {
        webAuthN_ = value;
      }
    }

    /// <summary>Field number for the "otp_sms" field.</summary>
    public const int OtpSmsFieldNumber = 2;
    private global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS otpSms_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS OtpSms {
      get { return otpSms_; }
      set {
        otpSms_ = value;
      }
    }

    /// <summary>Field number for the "otp_email" field.</summary>
    public const int OtpEmailFieldNumber = 3;
    private global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail otpEmail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail OtpEmail {
      get { return otpEmail_; }
      set {
        otpEmail_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RequestChallenges);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RequestChallenges other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(WebAuthN, other.WebAuthN)) return false;
      if (!object.Equals(OtpSms, other.OtpSms)) return false;
      if (!object.Equals(OtpEmail, other.OtpEmail)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (webAuthN_ != null) hash ^= WebAuthN.GetHashCode();
      if (otpSms_ != null) hash ^= OtpSms.GetHashCode();
      if (otpEmail_ != null) hash ^= OtpEmail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (webAuthN_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(WebAuthN);
      }
      if (otpSms_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OtpSms);
      }
      if (otpEmail_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OtpEmail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (webAuthN_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(WebAuthN);
      }
      if (otpSms_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(OtpSms);
      }
      if (otpEmail_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(OtpEmail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (webAuthN_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WebAuthN);
      }
      if (otpSms_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OtpSms);
      }
      if (otpEmail_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OtpEmail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RequestChallenges other) {
      if (other == null) {
        return;
      }
      if (other.webAuthN_ != null) {
        if (webAuthN_ == null) {
          WebAuthN = new global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN();
        }
        WebAuthN.MergeFrom(other.WebAuthN);
      }
      if (other.otpSms_ != null) {
        if (otpSms_ == null) {
          OtpSms = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS();
        }
        OtpSms.MergeFrom(other.OtpSms);
      }
      if (other.otpEmail_ != null) {
        if (otpEmail_ == null) {
          OtpEmail = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail();
        }
        OtpEmail.MergeFrom(other.OtpEmail);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (webAuthN_ == null) {
              WebAuthN = new global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN();
            }
            input.ReadMessage(WebAuthN);
            break;
          }
          case 18: {
            if (otpSms_ == null) {
              OtpSms = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS();
            }
            input.ReadMessage(OtpSms);
            break;
          }
          case 26: {
            if (otpEmail_ == null) {
              OtpEmail = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail();
            }
            input.ReadMessage(OtpEmail);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (webAuthN_ == null) {
              WebAuthN = new global::Zitadel.Session.V2.RequestChallenges.Types.WebAuthN();
            }
            input.ReadMessage(WebAuthN);
            break;
          }
          case 18: {
            if (otpSms_ == null) {
              OtpSms = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPSMS();
            }
            input.ReadMessage(OtpSms);
            break;
          }
          case 26: {
            if (otpEmail_ == null) {
              OtpEmail = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail();
            }
            input.ReadMessage(OtpEmail);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the RequestChallenges message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class WebAuthN : pb::IMessage<WebAuthN>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<WebAuthN> _parser = new pb::MessageParser<WebAuthN>(() => new WebAuthN());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<WebAuthN> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Zitadel.Session.V2.RequestChallenges.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN(WebAuthN other) : this() {
          domain_ = other.domain_;
          userVerificationRequirement_ = other.userVerificationRequirement_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN Clone() {
          return new WebAuthN(this);
        }

        /// <summary>Field number for the "domain" field.</summary>
        public const int DomainFieldNumber = 1;
        private string domain_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Domain {
          get { return domain_; }
          set {
            domain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "user_verification_requirement" field.</summary>
        public const int UserVerificationRequirementFieldNumber = 2;
        private global::Zitadel.Session.V2.UserVerificationRequirement userVerificationRequirement_ = global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Zitadel.Session.V2.UserVerificationRequirement UserVerificationRequirement {
          get { return userVerificationRequirement_; }
          set {
            userVerificationRequirement_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as WebAuthN);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(WebAuthN other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Domain != other.Domain) return false;
          if (UserVerificationRequirement != other.UserVerificationRequirement) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (Domain.Length != 0) hash ^= Domain.GetHashCode();
          if (UserVerificationRequirement != global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified) hash ^= UserVerificationRequirement.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (Domain.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Domain);
          }
          if (UserVerificationRequirement != global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified) {
            output.WriteRawTag(16);
            output.WriteEnum((int) UserVerificationRequirement);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (Domain.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Domain);
          }
          if (UserVerificationRequirement != global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified) {
            output.WriteRawTag(16);
            output.WriteEnum((int) UserVerificationRequirement);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (Domain.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Domain);
          }
          if (UserVerificationRequirement != global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified) {
            size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UserVerificationRequirement);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(WebAuthN other) {
          if (other == null) {
            return;
          }
          if (other.Domain.Length != 0) {
            Domain = other.Domain;
          }
          if (other.UserVerificationRequirement != global::Zitadel.Session.V2.UserVerificationRequirement.Unspecified) {
            UserVerificationRequirement = other.UserVerificationRequirement;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Domain = input.ReadString();
                break;
              }
              case 16: {
                UserVerificationRequirement = (global::Zitadel.Session.V2.UserVerificationRequirement) input.ReadEnum();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                Domain = input.ReadString();
                break;
              }
              case 16: {
                UserVerificationRequirement = (global::Zitadel.Session.V2.UserVerificationRequirement) input.ReadEnum();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class OTPSMS : pb::IMessage<OTPSMS>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<OTPSMS> _parser = new pb::MessageParser<OTPSMS>(() => new OTPSMS());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<OTPSMS> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Zitadel.Session.V2.RequestChallenges.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPSMS() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPSMS(OTPSMS other) : this() {
          returnCode_ = other.returnCode_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPSMS Clone() {
          return new OTPSMS(this);
        }

        /// <summary>Field number for the "return_code" field.</summary>
        public const int ReturnCodeFieldNumber = 1;
        private bool returnCode_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool ReturnCode {
          get { return returnCode_; }
          set {
            returnCode_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as OTPSMS);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(OTPSMS other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (ReturnCode != other.ReturnCode) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ReturnCode != false) hash ^= ReturnCode.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ReturnCode != false) {
            output.WriteRawTag(8);
            output.WriteBool(ReturnCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ReturnCode != false) {
            output.WriteRawTag(8);
            output.WriteBool(ReturnCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ReturnCode != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(OTPSMS other) {
          if (other == null) {
            return;
          }
          if (other.ReturnCode != false) {
            ReturnCode = other.ReturnCode;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                ReturnCode = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                ReturnCode = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class OTPEmail : pb::IMessage<OTPEmail>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<OTPEmail> _parser = new pb::MessageParser<OTPEmail>(() => new OTPEmail());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<OTPEmail> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Zitadel.Session.V2.RequestChallenges.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPEmail() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPEmail(OTPEmail other) : this() {
          switch (other.DeliveryTypeCase) {
            case DeliveryTypeOneofCase.SendCode:
              SendCode = other.SendCode.Clone();
              break;
            case DeliveryTypeOneofCase.ReturnCode:
              ReturnCode = other.ReturnCode.Clone();
              break;
          }

          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OTPEmail Clone() {
          return new OTPEmail(this);
        }

        /// <summary>Field number for the "send_code" field.</summary>
        public const int SendCodeFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode SendCode {
          get { return deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode ? (global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode) deliveryType_ : null; }
          set {
            deliveryType_ = value;
            deliveryTypeCase_ = value == null ? DeliveryTypeOneofCase.None : DeliveryTypeOneofCase.SendCode;
          }
        }

        /// <summary>Field number for the "return_code" field.</summary>
        public const int ReturnCodeFieldNumber = 3;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode ReturnCode {
          get { return deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode ? (global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode) deliveryType_ : null; }
          set {
            deliveryType_ = value;
            deliveryTypeCase_ = value == null ? DeliveryTypeOneofCase.None : DeliveryTypeOneofCase.ReturnCode;
          }
        }

        private object deliveryType_;
        /// <summary>Enum of possible cases for the "delivery_type" oneof.</summary>
        public enum DeliveryTypeOneofCase {
          None = 0,
          SendCode = 2,
          ReturnCode = 3,
        }
        private DeliveryTypeOneofCase deliveryTypeCase_ = DeliveryTypeOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public DeliveryTypeOneofCase DeliveryTypeCase {
          get { return deliveryTypeCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void ClearDeliveryType() {
          deliveryTypeCase_ = DeliveryTypeOneofCase.None;
          deliveryType_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as OTPEmail);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(OTPEmail other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(SendCode, other.SendCode)) return false;
          if (!object.Equals(ReturnCode, other.ReturnCode)) return false;
          if (DeliveryTypeCase != other.DeliveryTypeCase) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) hash ^= SendCode.GetHashCode();
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) hash ^= ReturnCode.GetHashCode();
          hash ^= (int) deliveryTypeCase_;
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) {
            output.WriteRawTag(18);
            output.WriteMessage(SendCode);
          }
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) {
            output.WriteRawTag(26);
            output.WriteMessage(ReturnCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) {
            output.WriteRawTag(18);
            output.WriteMessage(SendCode);
          }
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) {
            output.WriteRawTag(26);
            output.WriteMessage(ReturnCode);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(SendCode);
          }
          if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReturnCode);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(OTPEmail other) {
          if (other == null) {
            return;
          }
          switch (other.DeliveryTypeCase) {
            case DeliveryTypeOneofCase.SendCode:
              if (SendCode == null) {
                SendCode = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode();
              }
              SendCode.MergeFrom(other.SendCode);
              break;
            case DeliveryTypeOneofCase.ReturnCode:
              if (ReturnCode == null) {
                ReturnCode = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode();
              }
              ReturnCode.MergeFrom(other.ReturnCode);
              break;
          }

          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 18: {
                global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode subBuilder = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode();
                if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) {
                  subBuilder.MergeFrom(SendCode);
                }
                input.ReadMessage(subBuilder);
                SendCode = subBuilder;
                break;
              }
              case 26: {
                global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode subBuilder = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode();
                if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) {
                  subBuilder.MergeFrom(ReturnCode);
                }
                input.ReadMessage(subBuilder);
                ReturnCode = subBuilder;
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 18: {
                global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode subBuilder = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.SendCode();
                if (deliveryTypeCase_ == DeliveryTypeOneofCase.SendCode) {
                  subBuilder.MergeFrom(SendCode);
                }
                input.ReadMessage(subBuilder);
                SendCode = subBuilder;
                break;
              }
              case 26: {
                global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode subBuilder = new global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Types.ReturnCode();
                if (deliveryTypeCase_ == DeliveryTypeOneofCase.ReturnCode) {
                  subBuilder.MergeFrom(ReturnCode);
                }
                input.ReadMessage(subBuilder);
                ReturnCode = subBuilder;
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the OTPEmail message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class SendCode : pb::IMessage<SendCode>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<SendCode> _parser = new pb::MessageParser<SendCode>(() => new SendCode());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<SendCode> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SendCode() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SendCode(SendCode other) : this() {
              urlTemplate_ = other.urlTemplate_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public SendCode Clone() {
              return new SendCode(this);
            }

            /// <summary>Field number for the "url_template" field.</summary>
            public const int UrlTemplateFieldNumber = 1;
            private readonly static string UrlTemplateDefaultValue = "";

            private string urlTemplate_;
            /// <summary>
            /// Optionally set a url_template, which will be used in the mail sent by ZITADEL to guide the user to your verification page.
            /// If no template is set, the default ZITADEL url will be used.
            ///
            /// The following placeholders can be used: Code, UserID, LoginName, DisplayName, PreferredLanguage, SessionID
            /// </summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public string UrlTemplate {
              get { return urlTemplate_ ?? UrlTemplateDefaultValue; }
              set {
                urlTemplate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }
            /// <summary>Gets whether the "url_template" field is set</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool HasUrlTemplate {
              get { return urlTemplate_ != null; }
            }
            /// <summary>Clears the value of the "url_template" field</summary>
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void ClearUrlTemplate() {
              urlTemplate_ = null;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as SendCode);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(SendCode other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (UrlTemplate != other.UrlTemplate) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (HasUrlTemplate) hash ^= UrlTemplate.GetHashCode();
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (HasUrlTemplate) {
                output.WriteRawTag(10);
                output.WriteString(UrlTemplate);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (HasUrlTemplate) {
                output.WriteRawTag(10);
                output.WriteString(UrlTemplate);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (HasUrlTemplate) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(UrlTemplate);
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(SendCode other) {
              if (other == null) {
                return;
              }
              if (other.HasUrlTemplate) {
                UrlTemplate = other.UrlTemplate;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    UrlTemplate = input.ReadString();
                    break;
                  }
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                  case 10: {
                    UrlTemplate = input.ReadString();
                    break;
                  }
                }
              }
            }
            #endif

          }

          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class ReturnCode : pb::IMessage<ReturnCode>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<ReturnCode> _parser = new pb::MessageParser<ReturnCode>(() => new ReturnCode());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<ReturnCode> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Zitadel.Session.V2.RequestChallenges.Types.OTPEmail.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ReturnCode() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ReturnCode(ReturnCode other) : this() {
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public ReturnCode Clone() {
              return new ReturnCode(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as ReturnCode);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(ReturnCode other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(ReturnCode other) {
              if (other == null) {
                return;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
              if ((tag & 7) == 4) {
                // Abort on any end group tag.
                return;
              }
              switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Challenges : pb::IMessage<Challenges>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Challenges> _parser = new pb::MessageParser<Challenges>(() => new Challenges());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Challenges> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Session.V2.ChallengeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Challenges() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Challenges(Challenges other) : this() {
      webAuthN_ = other.webAuthN_ != null ? other.webAuthN_.Clone() : null;
      otpSms_ = other.otpSms_;
      otpEmail_ = other.otpEmail_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Challenges Clone() {
      return new Challenges(this);
    }

    /// <summary>Field number for the "web_auth_n" field.</summary>
    public const int WebAuthNFieldNumber = 1;
    private global::Zitadel.Session.V2.Challenges.Types.WebAuthN webAuthN_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Session.V2.Challenges.Types.WebAuthN WebAuthN {
      get { return webAuthN_; }
      set {
        webAuthN_ = value;
      }
    }

    /// <summary>Field number for the "otp_sms" field.</summary>
    public const int OtpSmsFieldNumber = 2;
    private readonly static string OtpSmsDefaultValue = "";

    private string otpSms_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OtpSms {
      get { return otpSms_ ?? OtpSmsDefaultValue; }
      set {
        otpSms_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "otp_sms" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOtpSms {
      get { return otpSms_ != null; }
    }
    /// <summary>Clears the value of the "otp_sms" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOtpSms() {
      otpSms_ = null;
    }

    /// <summary>Field number for the "otp_email" field.</summary>
    public const int OtpEmailFieldNumber = 3;
    private readonly static string OtpEmailDefaultValue = "";

    private string otpEmail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OtpEmail {
      get { return otpEmail_ ?? OtpEmailDefaultValue; }
      set {
        otpEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "otp_email" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOtpEmail {
      get { return otpEmail_ != null; }
    }
    /// <summary>Clears the value of the "otp_email" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOtpEmail() {
      otpEmail_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Challenges);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Challenges other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(WebAuthN, other.WebAuthN)) return false;
      if (OtpSms != other.OtpSms) return false;
      if (OtpEmail != other.OtpEmail) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (webAuthN_ != null) hash ^= WebAuthN.GetHashCode();
      if (HasOtpSms) hash ^= OtpSms.GetHashCode();
      if (HasOtpEmail) hash ^= OtpEmail.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (webAuthN_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(WebAuthN);
      }
      if (HasOtpSms) {
        output.WriteRawTag(18);
        output.WriteString(OtpSms);
      }
      if (HasOtpEmail) {
        output.WriteRawTag(26);
        output.WriteString(OtpEmail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (webAuthN_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(WebAuthN);
      }
      if (HasOtpSms) {
        output.WriteRawTag(18);
        output.WriteString(OtpSms);
      }
      if (HasOtpEmail) {
        output.WriteRawTag(26);
        output.WriteString(OtpEmail);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (webAuthN_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WebAuthN);
      }
      if (HasOtpSms) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OtpSms);
      }
      if (HasOtpEmail) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OtpEmail);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Challenges other) {
      if (other == null) {
        return;
      }
      if (other.webAuthN_ != null) {
        if (webAuthN_ == null) {
          WebAuthN = new global::Zitadel.Session.V2.Challenges.Types.WebAuthN();
        }
        WebAuthN.MergeFrom(other.WebAuthN);
      }
      if (other.HasOtpSms) {
        OtpSms = other.OtpSms;
      }
      if (other.HasOtpEmail) {
        OtpEmail = other.OtpEmail;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (webAuthN_ == null) {
              WebAuthN = new global::Zitadel.Session.V2.Challenges.Types.WebAuthN();
            }
            input.ReadMessage(WebAuthN);
            break;
          }
          case 18: {
            OtpSms = input.ReadString();
            break;
          }
          case 26: {
            OtpEmail = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (webAuthN_ == null) {
              WebAuthN = new global::Zitadel.Session.V2.Challenges.Types.WebAuthN();
            }
            input.ReadMessage(WebAuthN);
            break;
          }
          case 18: {
            OtpSms = input.ReadString();
            break;
          }
          case 26: {
            OtpEmail = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Challenges message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class WebAuthN : pb::IMessage<WebAuthN>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<WebAuthN> _parser = new pb::MessageParser<WebAuthN>(() => new WebAuthN());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<WebAuthN> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Zitadel.Session.V2.Challenges.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN(WebAuthN other) : this() {
          publicKeyCredentialRequestOptions_ = other.publicKeyCredentialRequestOptions_ != null ? other.publicKeyCredentialRequestOptions_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public WebAuthN Clone() {
          return new WebAuthN(this);
        }

        /// <summary>Field number for the "public_key_credential_request_options" field.</summary>
        public const int PublicKeyCredentialRequestOptionsFieldNumber = 1;
        private global::Google.Protobuf.WellKnownTypes.Struct publicKeyCredentialRequestOptions_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Google.Protobuf.WellKnownTypes.Struct PublicKeyCredentialRequestOptions {
          get { return publicKeyCredentialRequestOptions_; }
          set {
            publicKeyCredentialRequestOptions_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as WebAuthN);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(WebAuthN other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(PublicKeyCredentialRequestOptions, other.PublicKeyCredentialRequestOptions)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (publicKeyCredentialRequestOptions_ != null) hash ^= PublicKeyCredentialRequestOptions.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (publicKeyCredentialRequestOptions_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(PublicKeyCredentialRequestOptions);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (publicKeyCredentialRequestOptions_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(PublicKeyCredentialRequestOptions);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (publicKeyCredentialRequestOptions_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(PublicKeyCredentialRequestOptions);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(WebAuthN other) {
          if (other == null) {
            return;
          }
          if (other.publicKeyCredentialRequestOptions_ != null) {
            if (publicKeyCredentialRequestOptions_ == null) {
              PublicKeyCredentialRequestOptions = new global::Google.Protobuf.WellKnownTypes.Struct();
            }
            PublicKeyCredentialRequestOptions.MergeFrom(other.PublicKeyCredentialRequestOptions);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (publicKeyCredentialRequestOptions_ == null) {
                  PublicKeyCredentialRequestOptions = new global::Google.Protobuf.WellKnownTypes.Struct();
                }
                input.ReadMessage(PublicKeyCredentialRequestOptions);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (publicKeyCredentialRequestOptions_ == null) {
                  PublicKeyCredentialRequestOptions = new global::Google.Protobuf.WellKnownTypes.Struct();
                }
                input.ReadMessage(PublicKeyCredentialRequestOptions);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
