// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/saml/v2/saml_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Zitadel.Saml.V2 {
  public static partial class SAMLService
  {
    static readonly string __ServiceName = "zitadel.saml.v2.SAMLService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Zitadel.Saml.V2.GetSAMLRequestRequest> __Marshaller_zitadel_saml_v2_GetSAMLRequestRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Zitadel.Saml.V2.GetSAMLRequestRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Zitadel.Saml.V2.GetSAMLRequestResponse> __Marshaller_zitadel_saml_v2_GetSAMLRequestResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Zitadel.Saml.V2.GetSAMLRequestResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Zitadel.Saml.V2.CreateResponseRequest> __Marshaller_zitadel_saml_v2_CreateResponseRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Zitadel.Saml.V2.CreateResponseRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Zitadel.Saml.V2.CreateResponseResponse> __Marshaller_zitadel_saml_v2_CreateResponseResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Zitadel.Saml.V2.CreateResponseResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Zitadel.Saml.V2.GetSAMLRequestRequest, global::Zitadel.Saml.V2.GetSAMLRequestResponse> __Method_GetSAMLRequest = new grpc::Method<global::Zitadel.Saml.V2.GetSAMLRequestRequest, global::Zitadel.Saml.V2.GetSAMLRequestResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSAMLRequest",
        __Marshaller_zitadel_saml_v2_GetSAMLRequestRequest,
        __Marshaller_zitadel_saml_v2_GetSAMLRequestResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Zitadel.Saml.V2.CreateResponseRequest, global::Zitadel.Saml.V2.CreateResponseResponse> __Method_CreateResponse = new grpc::Method<global::Zitadel.Saml.V2.CreateResponseRequest, global::Zitadel.Saml.V2.CreateResponseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateResponse",
        __Marshaller_zitadel_saml_v2_CreateResponseRequest,
        __Marshaller_zitadel_saml_v2_CreateResponseResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Zitadel.Saml.V2.SamlServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SAMLService</summary>
    [grpc::BindServiceMethod(typeof(SAMLService), "BindService")]
    public abstract partial class SAMLServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Zitadel.Saml.V2.GetSAMLRequestResponse> GetSAMLRequest(global::Zitadel.Saml.V2.GetSAMLRequestRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Zitadel.Saml.V2.CreateResponseResponse> CreateResponse(global::Zitadel.Saml.V2.CreateResponseRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SAMLService</summary>
    public partial class SAMLServiceClient : grpc::ClientBase<SAMLServiceClient>
    {
      /// <summary>Creates a new client for SAMLService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SAMLServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SAMLService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public SAMLServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SAMLServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected SAMLServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Zitadel.Saml.V2.GetSAMLRequestResponse GetSAMLRequest(global::Zitadel.Saml.V2.GetSAMLRequestRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSAMLRequest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Zitadel.Saml.V2.GetSAMLRequestResponse GetSAMLRequest(global::Zitadel.Saml.V2.GetSAMLRequestRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSAMLRequest, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Zitadel.Saml.V2.GetSAMLRequestResponse> GetSAMLRequestAsync(global::Zitadel.Saml.V2.GetSAMLRequestRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSAMLRequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Zitadel.Saml.V2.GetSAMLRequestResponse> GetSAMLRequestAsync(global::Zitadel.Saml.V2.GetSAMLRequestRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSAMLRequest, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Zitadel.Saml.V2.CreateResponseResponse CreateResponse(global::Zitadel.Saml.V2.CreateResponseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateResponse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Zitadel.Saml.V2.CreateResponseResponse CreateResponse(global::Zitadel.Saml.V2.CreateResponseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateResponse, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Zitadel.Saml.V2.CreateResponseResponse> CreateResponseAsync(global::Zitadel.Saml.V2.CreateResponseRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateResponseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Zitadel.Saml.V2.CreateResponseResponse> CreateResponseAsync(global::Zitadel.Saml.V2.CreateResponseRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateResponse, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override SAMLServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SAMLServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(SAMLServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSAMLRequest, serviceImpl.GetSAMLRequest)
          .AddMethod(__Method_CreateResponse, serviceImpl.CreateResponse).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SAMLServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSAMLRequest, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Zitadel.Saml.V2.GetSAMLRequestRequest, global::Zitadel.Saml.V2.GetSAMLRequestResponse>(serviceImpl.GetSAMLRequest));
      serviceBinder.AddMethod(__Method_CreateResponse, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Zitadel.Saml.V2.CreateResponseRequest, global::Zitadel.Saml.V2.CreateResponseResponse>(serviceImpl.CreateResponse));
    }

  }
}
#endregion
