// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/settings/v2/lockout_settings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Settings.V2 {

  /// <summary>Holder for reflection information generated from zitadel/settings/v2/lockout_settings.proto</summary>
  public static partial class LockoutSettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/settings/v2/lockout_settings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LockoutSettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cip6aXRhZGVsL3NldHRpbmdzL3YyL2xvY2tvdXRfc2V0dGluZ3MucHJvdG8S",
            "E3ppdGFkZWwuc2V0dGluZ3MudjIaLnByb3RvYy1nZW4tb3BlbmFwaXYyL29w",
            "dGlvbnMvYW5ub3RhdGlvbnMucHJvdG8aInppdGFkZWwvc2V0dGluZ3MvdjIv",
            "c2V0dGluZ3MucHJvdG8i3QEKD0xvY2tvdXRTZXR0aW5ncxI9ChVtYXhfcGFz",
            "c3dvcmRfYXR0ZW1wdHMYASABKARCCZJBBkoEIjEwIlITbWF4UGFzc3dvcmRB",
            "dHRlbXB0cxJWChNyZXNvdXJjZV9vd25lcl90eXBlGAIgASgOMiYueml0YWRl",
            "bC5zZXR0aW5ncy52Mi5SZXNvdXJjZU93bmVyVHlwZVIRcmVzb3VyY2VPd25l",
            "clR5cGUSMwoQbWF4X290cF9hdHRlbXB0cxgDIAEoBEIJkkEGSgQiMTAiUg5t",
            "YXhPdHBBdHRlbXB0c0LXAQoXY29tLnppdGFkZWwuc2V0dGluZ3MudjJCFExv",
            "Y2tvdXRTZXR0aW5nc1Byb3RvUAFaOGdpdGh1Yi5jb20veml0YWRlbC96aXRh",
            "ZGVsL3BrZy9ncnBjL3NldHRpbmdzL3YyO3NldHRpbmdzogIDWlNYqgITWml0",
            "YWRlbC5TZXR0aW5ncy5WMsoCE1ppdGFkZWxcU2V0dGluZ3NcVjLiAh9aaXRh",
            "ZGVsXFNldHRpbmdzXFYyXEdQQk1ldGFkYXRh6gIVWml0YWRlbDo6U2V0dGlu",
            "Z3M6OlYyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Zitadel.Settings.V2.SettingsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Settings.V2.LockoutSettings), global::Zitadel.Settings.V2.LockoutSettings.Parser, new[]{ "MaxPasswordAttempts", "ResourceOwnerType", "MaxOtpAttempts" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LockoutSettings : pb::IMessage<LockoutSettings>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LockoutSettings> _parser = new pb::MessageParser<LockoutSettings>(() => new LockoutSettings());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LockoutSettings> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Settings.V2.LockoutSettingsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockoutSettings() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockoutSettings(LockoutSettings other) : this() {
      maxPasswordAttempts_ = other.maxPasswordAttempts_;
      resourceOwnerType_ = other.resourceOwnerType_;
      maxOtpAttempts_ = other.maxOtpAttempts_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LockoutSettings Clone() {
      return new LockoutSettings(this);
    }

    /// <summary>Field number for the "max_password_attempts" field.</summary>
    public const int MaxPasswordAttemptsFieldNumber = 1;
    private ulong maxPasswordAttempts_;
    /// <summary>
    /// The amount of failed password attempts before the account gets locked.
    /// Attempts are reset as soon as the password is entered correctly or the password is reset.
    /// If set to 0 the account will never be locked.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MaxPasswordAttempts {
      get { return maxPasswordAttempts_; }
      set {
        maxPasswordAttempts_ = value;
      }
    }

    /// <summary>Field number for the "resource_owner_type" field.</summary>
    public const int ResourceOwnerTypeFieldNumber = 2;
    private global::Zitadel.Settings.V2.ResourceOwnerType resourceOwnerType_ = global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified;
    /// <summary>
    /// ResourceOwnerType returns if the settings is managed on the organization explicitly or
    /// fell back on the instance settings.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Settings.V2.ResourceOwnerType ResourceOwnerType {
      get { return resourceOwnerType_; }
      set {
        resourceOwnerType_ = value;
      }
    }

    /// <summary>Field number for the "max_otp_attempts" field.</summary>
    public const int MaxOtpAttemptsFieldNumber = 3;
    private ulong maxOtpAttempts_;
    /// <summary>
    /// THe amount of failed OTP (TOTP, SMS, Email) attempts before the account gets locked.
    /// Attempts are reset as soon as the OTP is entered correctly.
    /// If set to 0 the account will never be locked.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MaxOtpAttempts {
      get { return maxOtpAttempts_; }
      set {
        maxOtpAttempts_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LockoutSettings);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LockoutSettings other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MaxPasswordAttempts != other.MaxPasswordAttempts) return false;
      if (ResourceOwnerType != other.ResourceOwnerType) return false;
      if (MaxOtpAttempts != other.MaxOtpAttempts) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MaxPasswordAttempts != 0UL) hash ^= MaxPasswordAttempts.GetHashCode();
      if (ResourceOwnerType != global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified) hash ^= ResourceOwnerType.GetHashCode();
      if (MaxOtpAttempts != 0UL) hash ^= MaxOtpAttempts.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MaxPasswordAttempts != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MaxPasswordAttempts);
      }
      if (ResourceOwnerType != global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResourceOwnerType);
      }
      if (MaxOtpAttempts != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(MaxOtpAttempts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MaxPasswordAttempts != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MaxPasswordAttempts);
      }
      if (ResourceOwnerType != global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ResourceOwnerType);
      }
      if (MaxOtpAttempts != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(MaxOtpAttempts);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MaxPasswordAttempts != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaxPasswordAttempts);
      }
      if (ResourceOwnerType != global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResourceOwnerType);
      }
      if (MaxOtpAttempts != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MaxOtpAttempts);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LockoutSettings other) {
      if (other == null) {
        return;
      }
      if (other.MaxPasswordAttempts != 0UL) {
        MaxPasswordAttempts = other.MaxPasswordAttempts;
      }
      if (other.ResourceOwnerType != global::Zitadel.Settings.V2.ResourceOwnerType.Unspecified) {
        ResourceOwnerType = other.ResourceOwnerType;
      }
      if (other.MaxOtpAttempts != 0UL) {
        MaxOtpAttempts = other.MaxOtpAttempts;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MaxPasswordAttempts = input.ReadUInt64();
            break;
          }
          case 16: {
            ResourceOwnerType = (global::Zitadel.Settings.V2.ResourceOwnerType) input.ReadEnum();
            break;
          }
          case 24: {
            MaxOtpAttempts = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MaxPasswordAttempts = input.ReadUInt64();
            break;
          }
          case 16: {
            ResourceOwnerType = (global::Zitadel.Settings.V2.ResourceOwnerType) input.ReadEnum();
            break;
          }
          case 24: {
            MaxOtpAttempts = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
