// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/feature/v2/feature_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Feature.V2 {

  /// <summary>Holder for reflection information generated from zitadel/feature/v2/feature_service.proto</summary>
  public static partial class FeatureServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/feature/v2/feature_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FeatureServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cih6aXRhZGVsL2ZlYXR1cmUvdjIvZmVhdHVyZV9zZXJ2aWNlLnByb3RvEhJ6",
            "aXRhZGVsLmZlYXR1cmUudjIaHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJv",
            "dG8aLnByb3RvYy1nZW4tb3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMu",
            "cHJvdG8aH3ppdGFkZWwvZmVhdHVyZS92Mi9zeXN0ZW0ucHJvdG8aIXppdGFk",
            "ZWwvZmVhdHVyZS92Mi9pbnN0YW5jZS5wcm90bxoleml0YWRlbC9mZWF0dXJl",
            "L3YyL29yZ2FuaXphdGlvbi5wcm90bxodeml0YWRlbC9mZWF0dXJlL3YyL3Vz",
            "ZXIucHJvdG8aK3ppdGFkZWwvcHJvdG9jX2dlbl96aXRhZGVsL3YyL29wdGlv",
            "bnMucHJvdG8y9xIKDkZlYXR1cmVTZXJ2aWNlErwBChFTZXRTeXN0ZW1GZWF0",
            "dXJlcxIsLnppdGFkZWwuZmVhdHVyZS52Mi5TZXRTeXN0ZW1GZWF0dXJlc1Jl",
            "cXVlc3QaLS56aXRhZGVsLmZlYXR1cmUudjIuU2V0U3lzdGVtRmVhdHVyZXNS",
            "ZXNwb25zZSJKkkENSgsKAzIwMBIECgJPS4q1GBgKFgoUc3lzdGVtLmZlYXR1",
            "cmUud3JpdGWC0+STAhgaEy92Mi9mZWF0dXJlcy9zeXN0ZW06ASoSwAEKE1Jl",
            "c2V0U3lzdGVtRmVhdHVyZXMSLi56aXRhZGVsLmZlYXR1cmUudjIuUmVzZXRT",
            "eXN0ZW1GZWF0dXJlc1JlcXVlc3QaLy56aXRhZGVsLmZlYXR1cmUudjIuUmVz",
            "ZXRTeXN0ZW1GZWF0dXJlc1Jlc3BvbnNlIkiSQQ1KCwoDMjAwEgQKAk9LirUY",
            "GQoXChVzeXN0ZW0uZmVhdHVyZS5kZWxldGWC0+STAhUqEy92Mi9mZWF0dXJl",
            "cy9zeXN0ZW0SsgEKEUdldFN5c3RlbUZlYXR1cmVzEiwueml0YWRlbC5mZWF0",
            "dXJlLnYyLkdldFN5c3RlbUZlYXR1cmVzUmVxdWVzdBotLnppdGFkZWwuZmVh",
            "dHVyZS52Mi5HZXRTeXN0ZW1GZWF0dXJlc1Jlc3BvbnNlIkCSQQ1KCwoDMjAw",
            "EgQKAk9LirUYEQoPCg1hdXRoZW50aWNhdGVkgtPkkwIVEhMvdjIvZmVhdHVy",
            "ZXMvc3lzdGVtEsEBChNTZXRJbnN0YW5jZUZlYXR1cmVzEi4ueml0YWRlbC5m",
            "ZWF0dXJlLnYyLlNldEluc3RhbmNlRmVhdHVyZXNSZXF1ZXN0Gi8ueml0YWRl",
            "bC5mZWF0dXJlLnYyLlNldEluc3RhbmNlRmVhdHVyZXNSZXNwb25zZSJJkkEN",
            "SgsKAzIwMBIECgJPS4q1GBUKEwoRaWFtLmZlYXR1cmUud3JpdGWC0+STAhoa",
            "FS92Mi9mZWF0dXJlcy9pbnN0YW5jZToBKhLFAQoVUmVzZXRJbnN0YW5jZUZl",
            "YXR1cmVzEjAueml0YWRlbC5mZWF0dXJlLnYyLlJlc2V0SW5zdGFuY2VGZWF0",
            "dXJlc1JlcXVlc3QaMS56aXRhZGVsLmZlYXR1cmUudjIuUmVzZXRJbnN0YW5j",
            "ZUZlYXR1cmVzUmVzcG9uc2UiR5JBDUoLCgMyMDASBAoCT0uKtRgWChQKEmlh",
            "bS5mZWF0dXJlLmRlbGV0ZYLT5JMCFyoVL3YyL2ZlYXR1cmVzL2luc3RhbmNl",
            "EroBChNHZXRJbnN0YW5jZUZlYXR1cmVzEi4ueml0YWRlbC5mZWF0dXJlLnYy",
            "LkdldEluc3RhbmNlRmVhdHVyZXNSZXF1ZXN0Gi8ueml0YWRlbC5mZWF0dXJl",
            "LnYyLkdldEluc3RhbmNlRmVhdHVyZXNSZXNwb25zZSJCkkENSgsKAzIwMBIE",
            "CgJPS4q1GBEKDwoNYXV0aGVudGljYXRlZILT5JMCFxIVL3YyL2ZlYXR1cmVz",
            "L2luc3RhbmNlEuMBChdTZXRPcmdhbml6YXRpb25GZWF0dXJlcxIyLnppdGFk",
            "ZWwuZmVhdHVyZS52Mi5TZXRPcmdhbml6YXRpb25GZWF0dXJlc1JlcXVlc3Qa",
            "My56aXRhZGVsLmZlYXR1cmUudjIuU2V0T3JnYW5pemF0aW9uRmVhdHVyZXNS",
            "ZXNwb25zZSJfkkENSgsKAzIwMBIECgJPS4q1GBUKEwoRb3JnLmZlYXR1cmUu",
            "d3JpdGWC0+STAjAaKy92Mi9mZWF0dXJlcy9vcmdhbml6YXRpb24ve29yZ2Fu",
            "aXphdGlvbl9pZH06ASoS5wEKGVJlc2V0T3JnYW5pemF0aW9uRmVhdHVyZXMS",
            "NC56aXRhZGVsLmZlYXR1cmUudjIuUmVzZXRPcmdhbml6YXRpb25GZWF0dXJl",
            "c1JlcXVlc3QaNS56aXRhZGVsLmZlYXR1cmUudjIuUmVzZXRPcmdhbml6YXRp",
            "b25GZWF0dXJlc1Jlc3BvbnNlIl2SQQ1KCwoDMjAwEgQKAk9LirUYFgoUChJv",
            "cmcuZmVhdHVyZS5kZWxldGWC0+STAi0qKy92Mi9mZWF0dXJlcy9vcmdhbml6",
            "YXRpb24ve29yZ2FuaXphdGlvbl9pZH0S3AEKF0dldE9yZ2FuaXphdGlvbkZl",
            "YXR1cmVzEjIueml0YWRlbC5mZWF0dXJlLnYyLkdldE9yZ2FuaXphdGlvbkZl",
            "YXR1cmVzUmVxdWVzdBozLnppdGFkZWwuZmVhdHVyZS52Mi5HZXRPcmdhbml6",
            "YXRpb25GZWF0dXJlc1Jlc3BvbnNlIliSQQ1KCwoDMjAwEgQKAk9LirUYEQoP",
            "Cg1hdXRoZW50aWNhdGVkgtPkkwItEisvdjIvZmVhdHVyZXMvb3JnYW5pemF0",
            "aW9uL3tvcmdhbml6YXRpb25faWR9ErsBCg9TZXRVc2VyRmVhdHVyZXMSKS56",
            "aXRhZGVsLmZlYXR1cmUudjIuU2V0VXNlckZlYXR1cmVSZXF1ZXN0Gisueml0",
            "YWRlbC5mZWF0dXJlLnYyLlNldFVzZXJGZWF0dXJlc1Jlc3BvbnNlIlCSQQ1K",
            "CwoDMjAwEgQKAk9LirUYFgoUChJ1c2VyLmZlYXR1cmUud3JpdGWC0+STAiAa",
            "Gy92Mi9mZWF0dXJlcy91c2VyL3t1c2VyX2lkfToBKhLAAQoRUmVzZXRVc2Vy",
            "RmVhdHVyZXMSLC56aXRhZGVsLmZlYXR1cmUudjIuUmVzZXRVc2VyRmVhdHVy",
            "ZXNSZXF1ZXN0Gi0ueml0YWRlbC5mZWF0dXJlLnYyLlJlc2V0VXNlckZlYXR1",
            "cmVzUmVzcG9uc2UiTpJBDUoLCgMyMDASBAoCT0uKtRgXChUKE3VzZXIuZmVh",
            "dHVyZS5kZWxldGWC0+STAh0qGy92Mi9mZWF0dXJlcy91c2VyL3t1c2VyX2lk",
            "fRK0AQoPR2V0VXNlckZlYXR1cmVzEioueml0YWRlbC5mZWF0dXJlLnYyLkdl",
            "dFVzZXJGZWF0dXJlc1JlcXVlc3QaKy56aXRhZGVsLmZlYXR1cmUudjIuR2V0",
            "VXNlckZlYXR1cmVzUmVzcG9uc2UiSJJBDUoLCgMyMDASBAoCT0uKtRgRCg8K",
            "DWF1dGhlbnRpY2F0ZWSC0+STAh0SGy92Mi9mZWF0dXJlcy91c2VyL3t1c2Vy",
            "X2lkfUKLDgoWY29tLnppdGFkZWwuZmVhdHVyZS52MkITRmVhdHVyZVNlcnZp",
            "Y2VQcm90b1ABWjZnaXRodWIuY29tL3ppdGFkZWwveml0YWRlbC9wa2cvZ3Jw",
            "Yy9mZWF0dXJlL3YyO2ZlYXR1cmWiAgNaRliqAhJaaXRhZGVsLkZlYXR1cmUu",
            "VjLKAhJaaXRhZGVsXEZlYXR1cmVcVjLiAh5aaXRhZGVsXEZlYXR1cmVcVjJc",
            "R1BCTWV0YWRhdGHqAhRaaXRhZGVsOjpGZWF0dXJlOjpWMpJBuAwS2gYKD0Zl",
            "YXR1cmUgU2VydmljZRLIBVRoaXMgQVBJIGlzIGludGVuZGVkIHRvIG1hbmFn",
            "ZSBmZWF0dXJlcyBmb3IgWklUQURFTC4gRmVhdHVyZSBzZXR0aW5ncyB0aGF0",
            "IGFyZSBhdmFpbGFibGUgb24gbXVsdGlwbGUgImxldmVscyIsIHN1Y2ggYXMg",
            "aW5zdGFuY2UgYW5kIG9yZ2FuaXphdGlvbi4gVGhlIGhpZ2hlciBsZXZlbCBp",
            "bnN0YW5jZSBhY3RzIGFzIGEgZGVmYXVsdCBmb3IgdGhlIGxvd2VyIGxldmVs",
            "LiBXaGVuIGEgZmVhdHVyZSBpcyBzZXQgb24gbXVsdGlwbGUgbGV2ZWxzLCB0",
            "aGUgbG93ZXIgbGV2ZWwgdGFrZXMgcHJlY2VkZW5jZS4gRmVhdHVyZXMgY2Fu",
            "IGJlIGV4cGVyaW1lbnRhbCB3aGVyZSBaSVRBREVMIHdpbGwgYXNzdW1lIGEg",
            "c2FuZSBkZWZhdWx0LCBzdWNoIGFzIGRpc2FibGVkLiBXaGVuIG92ZXIgdGlt",
            "ZSBjb25maWRlbmNlIGluIHN1Y2ggYSBmZWF0dXJlIGdyb3dzLCBaSVRBREVM",
            "IGNhbiBkZWZhdWx0IHRvIGVuYWJsaW5nIHRoZSBmZWF0dXJlLiBBcyBhIGZp",
            "bmFsIHN0ZXAgd2UgbWlnaHQgY2hvb3NlIHRvIGFsd2F5cyBlbmFibGUgYSBm",
            "ZWF0dXJlIGFuZCByZW1vdmUgdGhlIHNldHRpbmcgZnJvbSB0aGlzIEFQSSwg",
            "cmVzZXJ2aW5nIHRoZSBwcm90byBmaWVsZCBudW1iZXIuIFN1Y2ggcmVtb3Zh",
            "bCBpcyBub3QgY29uc2lkZXJlZCBhIGJyZWFraW5nIGNoYW5nZS4gU2V0dGlu",
            "ZyBhIHJlbW92ZWQgZmllbGQgd2lsbCBlZmZlY3RpdmVseSByZXN1bHQgaW4g",
            "YSBuby1vcC4iLgoHWklUQURFTBITaHR0cHM6Ly96aXRhZGVsLmNvbRoOaGlA",
            "eml0YWRlbC5jb20qRwoKQXBhY2hlIDIuMBI5aHR0cHM6Ly9naXRodWIuY29t",
            "L3ppdGFkZWwveml0YWRlbC9ibG9iL21haW4vTElDRU5TSU5HLm1kMgMyLjAa",
            "DiRDVVNUT00tRE9NQUlOIgEvKgICATIQYXBwbGljYXRpb24vanNvbjIQYXBw",
            "bGljYXRpb24vZ3JwYzIaYXBwbGljYXRpb24vZ3JwYy13ZWIrcHJvdG86EGFw",
            "cGxpY2F0aW9uL2pzb246EGFwcGxpY2F0aW9uL2dycGM6GmFwcGxpY2F0aW9u",
            "L2dycGMtd2ViK3Byb3RvUm0KAzQwMxJmCkdSZXR1cm5lZCB3aGVuIHRoZSB1",
            "c2VyIGRvZXMgbm90IGhhdmUgcGVybWlzc2lvbiB0byBhY2Nlc3MgdGhlIHJl",
            "c291cmNlLhIbChkaFyMvZGVmaW5pdGlvbnMvcnBjU3RhdHVzUosBCgM0MDQS",
            "gwEKZFJldHVybmVkIHdoZW4gdGhlIHJlc291cmNlIGhhcyBubyBmZWF0dXJl",
            "IGZsYWcgc2V0dGluZ3MgYW5kIGluaGVyaXRhbmNlIGZyb20gdGhlIHBhcmVu",
            "dCBpcyBkaXNhYmxlZC4SGwoZGhcjL2RlZmluaXRpb25zL3JwY1N0YXR1c1rC",
            "AQq/AQoGT0F1dGgyErQBCAMoBDIhJENVU1RPTS1ET01BSU4vb2F1dGgvdjIv",
            "YXV0aG9yaXplOh0kQ1VTVE9NLURPTUFJTi9vYXV0aC92Mi90b2tlbkJsChAK",
            "Bm9wZW5pZBIGb3BlbmlkClgKKnVybjp6aXRhZGVsOmlhbTpvcmc6cHJvamVj",
            "dDppZDp6aXRhZGVsOmF1ZBIqdXJuOnppdGFkZWw6aWFtOm9yZzpwcm9qZWN0",
            "OmlkOnppdGFkZWw6YXVkYkAKPgoGT0F1dGgyEjQKBm9wZW5pZAoqdXJuOnpp",
            "dGFkZWw6aWFtOm9yZzpwcm9qZWN0OmlkOnppdGFkZWw6YXVkcj4KIkRldGFp",
            "bGVkIGluZm9ybWF0aW9uIGFib3V0IFpJVEFERUwSGGh0dHBzOi8veml0YWRl",
            "bC5jb20vZG9jc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, global::Zitadel.Feature.V2.SystemReflection.Descriptor, global::Zitadel.Feature.V2.InstanceReflection.Descriptor, global::Zitadel.Feature.V2.OrganizationReflection.Descriptor, global::Zitadel.Feature.V2.UserReflection.Descriptor, global::Zitadel.ProtocGenZitadel.V2.OptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
