// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/milestone/v1/milestone.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Milestone.V1 {

  /// <summary>Holder for reflection information generated from zitadel/milestone/v1/milestone.proto</summary>
  public static partial class MilestoneReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/milestone/v1/milestone.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MilestoneReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiR6aXRhZGVsL21pbGVzdG9uZS92MS9taWxlc3RvbmUucHJvdG8SFHppdGFk",
            "ZWwubWlsZXN0b25lLnYxGhR6aXRhZGVsL29iamVjdC5wcm90bxoXdmFsaWRh",
            "dGUvdmFsaWRhdGUucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8aLnByb3RvYy1nZW4tb3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlv",
            "bnMucHJvdG8ikgEKCU1pbGVzdG9uZRI3CgR0eXBlGAIgASgOMiMueml0YWRl",
            "bC5taWxlc3RvbmUudjEuTWlsZXN0b25lVHlwZVIEdHlwZRI9CgxyZWFjaGVk",
            "X2RhdGUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wUgtyZWFj",
            "aGVkRGF0ZUoECAEQAlIHZGV0YWlscyJrCg5NaWxlc3RvbmVRdWVyeRJQChBp",
            "c19yZWFjaGVkX3F1ZXJ5GAEgASgLMiQueml0YWRlbC5taWxlc3RvbmUudjEu",
            "SXNSZWFjaGVkUXVlcnlIAFIOaXNSZWFjaGVkUXVlcnlCBwoFcXVlcnkiSAoO",
            "SXNSZWFjaGVkUXVlcnkSNgoHcmVhY2hlZBgBIAEoCEIckkEZMhdvbmx5IHJl",
            "YWNoZWQgbWlsZXN0b25lc1IHcmVhY2hlZCq6AgoNTWlsZXN0b25lVHlwZRIe",
            "ChpNSUxFU1RPTkVfVFlQRV9VTlNQRUNJRklFRBAAEiMKH01JTEVTVE9ORV9U",
            "WVBFX0lOU1RBTkNFX0NSRUFURUQQARI3CjNNSUxFU1RPTkVfVFlQRV9BVVRI",
            "RU5USUNBVElPTl9TVUNDRUVERURfT05fSU5TVEFOQ0UQAhIiCh5NSUxFU1RP",
            "TkVfVFlQRV9QUk9KRUNUX0NSRUFURUQQAxImCiJNSUxFU1RPTkVfVFlQRV9B",
            "UFBMSUNBVElPTl9DUkVBVEVEEAQSOgo2TUlMRVNUT05FX1RZUEVfQVVUSEVO",
            "VElDQVRJT05fU1VDQ0VFREVEX09OX0FQUExJQ0FUSU9OEAUSIwofTUlMRVNU",
            "T05FX1RZUEVfSU5TVEFOQ0VfREVMRVRFRBAGKoABChJNaWxlc3RvbmVGaWVs",
            "ZE5hbWUSJAogTUlMRVNUT05FX0ZJRUxEX05BTUVfVU5TUEVDSUZJRUQQABId",
            "ChlNSUxFU1RPTkVfRklFTERfTkFNRV9UWVBFEAESJQohTUlMRVNUT05FX0ZJ",
            "RUxEX05BTUVfUkVBQ0hFRF9EQVRFEAJCywEKGGNvbS56aXRhZGVsLm1pbGVz",
            "dG9uZS52MUIOTWlsZXN0b25lUHJvdG9QAVotZ2l0aHViLmNvbS96aXRhZGVs",
            "L3ppdGFkZWwvcGtnL2dycGMvbWlsZXN0b25logIDWk1YqgIUWml0YWRlbC5N",
            "aWxlc3RvbmUuVjHKAhRaaXRhZGVsXE1pbGVzdG9uZVxWMeICIFppdGFkZWxc",
            "TWlsZXN0b25lXFYxXEdQQk1ldGFkYXRh6gIWWml0YWRlbDo6TWlsZXN0b25l",
            "OjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zitadel.V1.ObjectReflection.Descriptor, global::Validate.ValidateReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zitadel.Milestone.V1.MilestoneType), typeof(global::Zitadel.Milestone.V1.MilestoneFieldName), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Milestone.V1.Milestone), global::Zitadel.Milestone.V1.Milestone.Parser, new[]{ "Type", "ReachedDate" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Milestone.V1.MilestoneQuery), global::Zitadel.Milestone.V1.MilestoneQuery.Parser, new[]{ "IsReachedQuery" }, new[]{ "Query" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Zitadel.Milestone.V1.IsReachedQuery), global::Zitadel.Milestone.V1.IsReachedQuery.Parser, new[]{ "Reached" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MilestoneType {
    [pbr::OriginalName("MILESTONE_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MILESTONE_TYPE_INSTANCE_CREATED")] InstanceCreated = 1,
    [pbr::OriginalName("MILESTONE_TYPE_AUTHENTICATION_SUCCEEDED_ON_INSTANCE")] AuthenticationSucceededOnInstance = 2,
    [pbr::OriginalName("MILESTONE_TYPE_PROJECT_CREATED")] ProjectCreated = 3,
    [pbr::OriginalName("MILESTONE_TYPE_APPLICATION_CREATED")] ApplicationCreated = 4,
    [pbr::OriginalName("MILESTONE_TYPE_AUTHENTICATION_SUCCEEDED_ON_APPLICATION")] AuthenticationSucceededOnApplication = 5,
    [pbr::OriginalName("MILESTONE_TYPE_INSTANCE_DELETED")] InstanceDeleted = 6,
  }

  public enum MilestoneFieldName {
    [pbr::OriginalName("MILESTONE_FIELD_NAME_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("MILESTONE_FIELD_NAME_TYPE")] Type = 1,
    [pbr::OriginalName("MILESTONE_FIELD_NAME_REACHED_DATE")] ReachedDate = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Milestone : pb::IMessage<Milestone>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Milestone> _parser = new pb::MessageParser<Milestone>(() => new Milestone());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Milestone> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Milestone.V1.MilestoneReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Milestone() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Milestone(Milestone other) : this() {
      type_ = other.type_;
      reachedDate_ = other.reachedDate_ != null ? other.reachedDate_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Milestone Clone() {
      return new Milestone(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Zitadel.Milestone.V1.MilestoneType type_ = global::Zitadel.Milestone.V1.MilestoneType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Milestone.V1.MilestoneType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "reached_date" field.</summary>
    public const int ReachedDateFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp reachedDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ReachedDate {
      get { return reachedDate_; }
      set {
        reachedDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Milestone);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Milestone other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(ReachedDate, other.ReachedDate)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Zitadel.Milestone.V1.MilestoneType.Unspecified) hash ^= Type.GetHashCode();
      if (reachedDate_ != null) hash ^= ReachedDate.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Zitadel.Milestone.V1.MilestoneType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (reachedDate_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReachedDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Zitadel.Milestone.V1.MilestoneType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (reachedDate_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReachedDate);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Zitadel.Milestone.V1.MilestoneType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (reachedDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReachedDate);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Milestone other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Zitadel.Milestone.V1.MilestoneType.Unspecified) {
        Type = other.Type;
      }
      if (other.reachedDate_ != null) {
        if (reachedDate_ == null) {
          ReachedDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ReachedDate.MergeFrom(other.ReachedDate);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            Type = (global::Zitadel.Milestone.V1.MilestoneType) input.ReadEnum();
            break;
          }
          case 26: {
            if (reachedDate_ == null) {
              ReachedDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ReachedDate);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 16: {
            Type = (global::Zitadel.Milestone.V1.MilestoneType) input.ReadEnum();
            break;
          }
          case 26: {
            if (reachedDate_ == null) {
              ReachedDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ReachedDate);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MilestoneQuery : pb::IMessage<MilestoneQuery>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MilestoneQuery> _parser = new pb::MessageParser<MilestoneQuery>(() => new MilestoneQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MilestoneQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Milestone.V1.MilestoneReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MilestoneQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MilestoneQuery(MilestoneQuery other) : this() {
      switch (other.QueryCase) {
        case QueryOneofCase.IsReachedQuery:
          IsReachedQuery = other.IsReachedQuery.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MilestoneQuery Clone() {
      return new MilestoneQuery(this);
    }

    /// <summary>Field number for the "is_reached_query" field.</summary>
    public const int IsReachedQueryFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Zitadel.Milestone.V1.IsReachedQuery IsReachedQuery {
      get { return queryCase_ == QueryOneofCase.IsReachedQuery ? (global::Zitadel.Milestone.V1.IsReachedQuery) query_ : null; }
      set {
        query_ = value;
        queryCase_ = value == null ? QueryOneofCase.None : QueryOneofCase.IsReachedQuery;
      }
    }

    private object query_;
    /// <summary>Enum of possible cases for the "query" oneof.</summary>
    public enum QueryOneofCase {
      None = 0,
      IsReachedQuery = 1,
    }
    private QueryOneofCase queryCase_ = QueryOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryOneofCase QueryCase {
      get { return queryCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearQuery() {
      queryCase_ = QueryOneofCase.None;
      query_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MilestoneQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MilestoneQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(IsReachedQuery, other.IsReachedQuery)) return false;
      if (QueryCase != other.QueryCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (queryCase_ == QueryOneofCase.IsReachedQuery) hash ^= IsReachedQuery.GetHashCode();
      hash ^= (int) queryCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (queryCase_ == QueryOneofCase.IsReachedQuery) {
        output.WriteRawTag(10);
        output.WriteMessage(IsReachedQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (queryCase_ == QueryOneofCase.IsReachedQuery) {
        output.WriteRawTag(10);
        output.WriteMessage(IsReachedQuery);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (queryCase_ == QueryOneofCase.IsReachedQuery) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(IsReachedQuery);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MilestoneQuery other) {
      if (other == null) {
        return;
      }
      switch (other.QueryCase) {
        case QueryOneofCase.IsReachedQuery:
          if (IsReachedQuery == null) {
            IsReachedQuery = new global::Zitadel.Milestone.V1.IsReachedQuery();
          }
          IsReachedQuery.MergeFrom(other.IsReachedQuery);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::Zitadel.Milestone.V1.IsReachedQuery subBuilder = new global::Zitadel.Milestone.V1.IsReachedQuery();
            if (queryCase_ == QueryOneofCase.IsReachedQuery) {
              subBuilder.MergeFrom(IsReachedQuery);
            }
            input.ReadMessage(subBuilder);
            IsReachedQuery = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::Zitadel.Milestone.V1.IsReachedQuery subBuilder = new global::Zitadel.Milestone.V1.IsReachedQuery();
            if (queryCase_ == QueryOneofCase.IsReachedQuery) {
              subBuilder.MergeFrom(IsReachedQuery);
            }
            input.ReadMessage(subBuilder);
            IsReachedQuery = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IsReachedQuery : pb::IMessage<IsReachedQuery>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IsReachedQuery> _parser = new pb::MessageParser<IsReachedQuery>(() => new IsReachedQuery());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IsReachedQuery> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Zitadel.Milestone.V1.MilestoneReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsReachedQuery() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsReachedQuery(IsReachedQuery other) : this() {
      reached_ = other.reached_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IsReachedQuery Clone() {
      return new IsReachedQuery(this);
    }

    /// <summary>Field number for the "reached" field.</summary>
    public const int ReachedFieldNumber = 1;
    private bool reached_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Reached {
      get { return reached_; }
      set {
        reached_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IsReachedQuery);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IsReachedQuery other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Reached != other.Reached) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Reached != false) hash ^= Reached.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Reached != false) {
        output.WriteRawTag(8);
        output.WriteBool(Reached);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Reached != false) {
        output.WriteRawTag(8);
        output.WriteBool(Reached);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Reached != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IsReachedQuery other) {
      if (other == null) {
        return;
      }
      if (other.Reached != false) {
        Reached = other.Reached;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Reached = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Reached = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
