// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: zitadel/settings/v2beta/settings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Zitadel.Settings.V2beta {

  /// <summary>Holder for reflection information generated from zitadel/settings/v2beta/settings.proto</summary>
  public static partial class SettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for zitadel/settings/v2beta/settings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZ6aXRhZGVsL3NldHRpbmdzL3YyYmV0YS9zZXR0aW5ncy5wcm90bxIXeml0",
            "YWRlbC5zZXR0aW5ncy52MmJldGEaLnByb3RvYy1nZW4tb3BlbmFwaXYyL29w",
            "dGlvbnMvYW5ub3RhdGlvbnMucHJvdG8qdwoRUmVzb3VyY2VPd25lclR5cGUS",
            "IwofUkVTT1VSQ0VfT1dORVJfVFlQRV9VTlNQRUNJRklFRBAAEiAKHFJFU09V",
            "UkNFX09XTkVSX1RZUEVfSU5TVEFOQ0UQARIbChdSRVNPVVJDRV9PV05FUl9U",
            "WVBFX09SRxACQugBChtjb20ueml0YWRlbC5zZXR0aW5ncy52MmJldGFCDVNl",
            "dHRpbmdzUHJvdG9QAVo8Z2l0aHViLmNvbS96aXRhZGVsL3ppdGFkZWwvcGtn",
            "L2dycGMvc2V0dGluZ3MvdjJiZXRhO3NldHRpbmdzogIDWlNYqgIXWml0YWRl",
            "bC5TZXR0aW5ncy5WMmJldGHKAhdaaXRhZGVsXFNldHRpbmdzXFYyYmV0YeIC",
            "I1ppdGFkZWxcU2V0dGluZ3NcVjJiZXRhXEdQQk1ldGFkYXRh6gIZWml0YWRl",
            "bDo6U2V0dGluZ3M6OlYyYmV0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Zitadel.Settings.V2beta.ResourceOwnerType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ResourceOwnerType {
    [pbr::OriginalName("RESOURCE_OWNER_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("RESOURCE_OWNER_TYPE_INSTANCE")] Instance = 1,
    [pbr::OriginalName("RESOURCE_OWNER_TYPE_ORG")] Org = 2,
  }

  #endregion

}

#endregion Designer generated code
